### ISSUE TITLE
Warning: React.createElement: type is invalid when used with webpack code splitting

### ISSUE THREAD

**Issue by pbarbiero** [sanniassin/react-input-mask#101]
When importing the component from separate code split bundles, *usually* the 2nd import will fail with this error:
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

This will then continue to error out until the client cache is entirely cleared and the app reloaded, only to reoccur once a second bundle loads it again.

This is only an issue when using webpack (or similar bundler) that honors the package.json `module` import.

`import MaskedInput from 'react-input-mask'` will trigger the issue
`import MaskedInput from 'react-input-mask/dist/react-input-mask.min';` will **not** trigger the issue

This does not reproduce 100% of the time, but from my testing and debugging until I pinpointed the source being the import it occurred roughly 80% of the time we loaded it from a second bundle.

*Environment*
react 15.5.4
webpack 3.3.0
react-input-mask 1.0.6

*Additional information:*
webpack is configured to code split the application up into multiple lazy loaded bundles, and we use `commonschunkplugin` to move all shared node_modules to an async vendor bundle as well which is loaded along with the entry bundle.

**Comment by sanniassin** [comment]
@pbarbiero Could you share your webpack config?

**Comment by pbarbiero** [comment]
If you really need the full config I can provide it to you privately, otherwise the only interesting piece that we have is this:

```
    new webpack.optimize.CommonsChunkPlugin({
      name: 'app',
      async: 'common',
      minChunks(module, count) {
        const context = module.context;
        return ((context && context.indexOf('node_modules') >= 0) || count >= 2);
      },
    }),
    new webpack.optimize.ModuleConcatenationPlugin(),
```

Otherwise its pretty standard piping anything not under node_modules through babel with the `["airbnb", {"modules": false}],` preset.

I wonder if it possibly could be related to webpack3 ModuleConcatenationPlugin, but I find that unlikely.

**Comment by sanniassin** [comment]
@pbarbiero Well, still can't reproduce after two hours. Can you make a demo?

BTW, does it fail with webpack 2.7.0?

**Comment by pbarbiero** [comment]
I wont have time until next week (middle of deployments currently) but I will try to narrow it down further then.  At the very least I will try changing versions of react-input-mask around and see if that makes it go away and come back.

If I cant narrow it down and if no one else reproduces, I will close this issue.

**Comment by pbarbiero** [comment]
Looks like it almost definitely was webpack moduleconcatenationplugin causing issues. Traced it back to this issue: https://github.com/webpack/webpack/issues/5314

Next webpack version should have it resolved.
