### ISSUE TITLE
Masking with '9' digit

### ISSUE THREAD

**Issue by batuhantozun** [sanniassin/react-input-mask#102]
I need to mask like a +90 (123) 123 12 12. But If i write  '9' after the '+' symbol, plugin starting to mask on this point. :)

How can i set default value to +90?

**Comment by Will-Sommers** [comment]
@batuhantozun I'm not a maintainer of this project but your mask would be:

`+99 (999) 999 99 99` and then you would need to pass in a `value` prop to the component that begins with `90`.

Something like 
```
render() {
  const value = "90" + this.props.valuel
  return (<InputElement
    mask="+99 (999) 999 99 99"
    value={value}
  />);
```

**Comment by sanniassin** [comment]
Prefix 9 with backslash.
```jsx
<InputMask mask="+\90 (999) 999 99 99" />
```
