### ISSUE TITLE
IE11 not registering all changes

### ISSUE THREAD

**Issue by Andrekra** [sanniassin/react-input-mask#103]
With a simple implementation:
``` <InputMask mask='99/99/9999' /> ```

When you fill in for example 12/12/2009 and hold down the backspace button, I end up with __/__/___9 most of the times, or sometimes even __/1_/___9

changing the ```onChange``` event to a```onInput``` resolves this issue. This only appears to be happening on IE 11 and could be related to React 15(.4) since the demo on gh pages works fine. (I found a bug relating to it in https://github.com/facebook/react/issues/7489) A found a similar fix here https://github.com/text-mask/text-mask/pull/164

**Comment by sanniassin** [comment]
@Andrekra It's definitely broken in React 15.4 but seems to be fixed in 15.6.1. Could you upgrade to the latest React and check?

**Comment by Andrekra** [comment]
Upgrading react to 15.6.1 didn't help, but upgrading react-dom to 15.6.1 did. Thanks!
