### ISSUE TITLE
Add the ability to focus on a masked element

### ISSUE THREAD

**Issue by Will-Sommers** [sanniassin/react-input-mask#105]
Hello, I would like to add the ability to focus on a masked element. I guess this would need to be done internally via a `ref` and passed in by the parent component and focused on `componentDidMount`. 

Are you accepting pull requests? 

Cheers,
Will

PS. Thank you for building this, it works well.

**Comment by rafael-vitor** [comment]
@Will-Sommers  I managed to do it like this:
```
<InputMask
  ref={(el) => { this.input = el; }}
/>
```
and calling: 
`this.input.getInputDOMNode().focus();`
getInputDOMNode: https://github.com/sanniassin/react-input-mask/blob/master/src/index.js#L114

**Comment by sanniassin** [comment]
Use [findDOMNode](https://reactjs.org/docs/react-dom.html#finddomnode) to get actual input element.

```jsx
import { Component } from 'react';
import { findDOMNode } from 'react-dom';
import InputMask from 'react-input-mask';

class Input extends Component {
  componentDidMount() {
    this.input.focus();
  }

  render() {
    return <InputMask mask="99-99-99" ref={ref => this.input = findDOMNode(ref)} />
  }
}
```

Actually, if you need to set focus right after mount, it can be done easier with autoFocus property:
```jsx
<InputMask mask="99-99-99" autoFocus />
```
