### ISSUE TITLE
Can't paste values over existing values

### ISSUE THREAD

**Issue by rtomchinsky** [sanniassin/react-input-mask#106]
When trying to paste a value over an existing value, and the new value length (without masking) is greater than the old value length (with masking), the new value will be cropped to the difference between the lengths e.g:

- mask: 999.999.999
- old value: 111
- new value: 222222222
- final value after paste: 111.222.222

After a little debugging, it appears as though the component is ignoring the paste event when not on android, so this.paste in `onChange` is `undefined`.

If I remove the whole value inside the `onPaste` prop, the value is then filled correctly.

**Comment by sanniassin** [comment]
@rtomchinsky Correct me if I wrong.

Clipboard contains "222222222" and you're trying to paste it into the same input as on screenshot, right? With cursor before first character and no selection.

If so, what is the browser and OS?

![image](https://user-images.githubusercontent.com/2291616/31942217-4685af06-b8cd-11e7-9eff-e7e9a20ce15b.png)

**Comment by rtomchinsky** [comment]
@sanniassin sorry, I meant that the whole value is selected. I'm trying to paste over the existing value, as in `111` -> `222.222.222`.

I'm running Chrome on Ubuntu 16.04.

**Comment by rtomchinsky** [comment]
@sanniassin I've changed the `onPaste` method to only call `this.setInputText('')` on Android, but still set `this.paste` everywhere. This corrected the issue, although now pasting "333" over:

![input](https://user-images.githubusercontent.com/2497755/31943902-fd5ac61e-b8a8-11e7-8e38-219bef92de05.png)

causes it to become "222.222.333"

**Comment by sanniassin** [comment]
@rtomchinsky Should be fixed in this snippet, check it out please
https://codesandbox.io/s/9v7689q64

**Comment by sanniassin** [comment]
@rtomchinsky Released 1.1.0 which is supposed to fix this issue. Reopen if it doesn't.
