### ISSUE TITLE
Inconsistent cursor positioning on focus

### ISSUE THREAD

**Issue by pbarbiero** [sanniassin/react-input-mask#108]
(See video here: http://recordit.co/Yx1bC0PVzQ)

When focusing a field (either with masks always visible or not) the initial cursor positioning is not consistent. It is expected to be at the first available character position every time it gains focus, however about 70% of the time the cursor will jump to the end, either immediately or after a fractional delay. The video should show this clearly. I simply am taking care to do a single click off the field, and on the field.

**Comment by alex-shamshurin** [comment]
Yep, it's very annoying

**Comment by sanniassin** [comment]
Usually it happens because browser moves it to the end on a slight mouse movement while button is pressed. I mean really slight which is hard to notice. Can you pay attention to that and check if it happens when you move mouse cursor into the input, hold it and then carefully click? And the second check is to place the mouse cursor over the first character in input and see if it jumps to start instead of end.

Can make workaround for that but need to make sure it won't interfere with actual selection.

**Comment by pbarbiero** [comment]
No, thats not it @sanniassin -- it happens very easily and very repeatable even when being extra cautious to not move the cursor after clicking.

I did some tracing a while back, and I am convinced its a chrome bug, the only way I could reliably eliminate it is switching from requestAnimationFrame to a timeout over 100ms, but obviously that is also not a good user experience.

**Comment by alex-shamshurin** [comment]
I happens sometimes without any mouse movements

**Comment by alex-shamshurin** [comment]
usually when user types fast

**Comment by sanniassin** [comment]
@alex-shamshurin Fast typing issue is different, so it's better to open another issue for it.

**Comment by pbarbiero** [comment]
Thats pretty wild. I am 100% sure I am not moving the mouse when clicking, and 90% of the time it will trigger the mousemove event.

In fact, if I position my cursor for a click, pick up my mouse (so it cant pick up movement) and click, I still get the mousemove event.

**Comment by sanniassin** [comment]
@pbarbiero Here's the version with a little threshold for both duration and distance of mouse movement. Does it work better for you?

https://codesandbox.io/s/nrx4jjz0p0

**Comment by pbarbiero** [comment]
Very cool, completely resolves it 100% of the time.

**Comment by sanniassin** [comment]
Great, I'll release it in a few days.

**Comment by sanniassin** [comment]
Released 1.1.0

**Comment by bartekczyz** [comment]
This still happens (mostly on Safari) when you have more `InputMask` components, see https://codesandbox.io/s/competent-wood-3c4n1

**Comment by bartekczyz** [comment]
@sanniassin can you please reopen this one?
