### ISSUE TITLE
E-mail mask

### ISSUE THREAD

**Issue by slavamukhin** [sanniassin/react-input-mask#109]
How write mask for e-mail address?

**Comment by dynnt27** [comment]
I need this one too.

**Comment by jimmywarting** [comment]
masking just a @ sign is little pointless just use the `<input type="email" placeholder="email@example.com">`

**Comment by tgmarinho** [comment]
if you are using material-ui-next:

` <TextField
            className="adjusting-margin"
            placeholder="email@example.com"
            type="email"
            name="email"
            label="Email"
            value={this.state.email}
            onChange={this.onInputChange}
            fullWidth
          />`

but the form is sent without error message....

**Comment by Katyi** [comment]
https://bobbyhadz.com/blog/react-check-if-email-is-valid#:~:text=To%20validate%20an%20email%20in,is%20valid%20and%20false%20otherwise.
