### ISSUE TITLE
Allow type='number' to be used for the input

### ISSUE THREAD

**Issue by variousauthors** [sanniassin/react-input-mask#110]
Awesome plugin, does the job. My one issue is that for ease of use on mobile I would like to be able to set the `type` field to `number` so that the number keypad comes up automatically. It's a small thing, but it makes the user experience of entering phone numbers, birthdays, and credit card info much nicer. As it stands, when I set `type='number'` I get:

```
Uncaught DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.
```

I'll be poking around in the days to come, and I'll update this if I come up with an easy fix or a PR.

**Comment by sanniassin** [comment]
Use type="tel" for number keyboard. "number" uses it's own format logic which isn't compatible with masking.

**Comment by pedrogaudencio** [comment]
Awesome plugin indeed! I'm experiencing the same issue as @variousauthors. @sanniassin I also tried using `type="tel"` and this is not included in the rendered output.

Here's the full element I'm using:
`<InputMask mask="9999-999" pattern="[0-9]{4}-[0-9]{3}" required placeholder="Insert Postal Code" className="postal-code input-text" type="tel" maskChar={null} value={this.state.postalCode} onChange={this.handleChange} />`. Is there anything I'm missing? Thanks!

**Comment by gimtonic** [comment]
Very good. Please write this on documentation.

**Comment by jSanchezHospy** [comment]
@sanniassin I added the "type=tel" to the component, but I don't see any difference; Safari still shows the full keyboard.
