### ISSUE TITLE
onChange is fired when the mask is shown on focus and hidden on blur

### ISSUE THREAD

**Issue by chumakoff** [sanniassin/react-input-mask#111]
When the input value is empty and the mask is getting shown on focus and getting hidden on blur, then onChange event is triggered.
 It shuldn't, because the actual value is not changing (staying empty).

**Comment by sanniassin** [comment]
It triggers to keep component value in sync with `value` prop. Otherwise you won't be able to handle things like custom placeholders which should be toggled when input value changes from empty to non-empty.

You can distinguish onFocus changes from regular ones by looking at event.type field:
```jsx
class Input extends React.Component {
  state = {
    value: ''
  }

  onChange = (event) => {
    if (event.type === 'focus' || event.type === 'blur') {
      // we aren't interested in such changes
      return;
    }

    this.setState({
      value: event.target.value
    });
  }

  render() {
    return <InputMask mask="9999-9999-9999" value={this.state.value} onChange={this.onChange} />;
  }
}
```
