### ISSUE TITLE
AutoFill Issues - A Digit Gets Dropped

### ISSUE THREAD

**Issue by pmn4** [sanniassin/react-input-mask#113]
When using AutoFill in combination with a prefix, you get an off-by-one error and a character gets dropped.

here's an example:
I am going to choose the phone number `(212) 123-1234`, and after applying the mask, I get `(212) 231-234` (notice the second "1" gets dropped)
![off-by-one](https://user-images.githubusercontent.com/1158287/34842356-3d673a12-f6d9-11e7-9208-fb80b4b28414.gif)

I believe this has to do with the following logic:
[`var oldValue = this.value;`](https://github.com/sanniassin/react-input-mask/blob/b275a52e6ab53e1b0b10efff4b8fdd413c81417d/src/index.js#L272)

There is an assumption that `this.value` is always current, but in the case of AutoFill, that is not the case. In the gif above, `this.value` is equal to `"(2"`, and therefore a substring operations starts with the third character. However, the input no longer has the leading `"("` so the substring operation is off by one.

One way to fix this could be to say:
``` JavaScript
var oldValue = event.currentTarget.value.indexOf(this.value) === 0 ? this.value : "";
```

**Comment by sanniassin** [comment]
Fixed in latest update

**Comment by pmn4** [comment]
awesome! thank you @sanniassin
