### ISSUE TITLE
webkit-autofill invalid syntax [firefox]

### ISSUE THREAD

**Issue by ambewas** [sanniassin/react-input-mask#115]
https://github.com/sanniassin/react-input-mask/commit/4db01eab221ab606d5b77dfc9c133bca2bc44ed5 

introduced a bug in firefox with `webkit-autofill` not being supported. 

error message:
`':-webkit-autofill' is not a valid selector"`

**Comment by sanniassin** [comment]
Thank you for the report. Fixed in 1.1.2
