### ISSUE TITLE
Chrome autofill not working properly with redux-frorm

### ISSUE THREAD

**Issue by StasVitAlex** [sanniassin/react-input-mask#127]
Chrome autofill not working properly with redux-frorm

**Comment by sanniassin** [comment]
Wrote [a section](https://github.com/sanniassin/react-input-mask#known-issues) in readme about issues with autofill.

**Comment by chuikoffru** [comment]
`
const formDefault = {
    phone : '',
    password: ''
  }

const [form, setForm] = useState(formDefault)

const changeHandler = e => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    })
  }

<InputMask
              mask={form.phone ? "+79999999999" : null}
              type="text"
              maskChar={null}
              id="phone"
              name="phone"
              placeholder="Номер телефона"
              required
              value={form.phone}
              onChange={e => e.preventDefault()}
              onInput={changeHandler}/>`

It really helped me make autofill of my input
