### ISSUE TITLE
When mask contains parentheses onChange doesn't work

### ISSUE THREAD

**Issue by guilhermehubner** [sanniassin/react-input-mask#128]
I try: 

```jsx
<InputMask  placeholder="(00) 00000-0000" mask="(99) 99999-9999" value={this.state.phone1}
   maxLength={15} onChange={this.handleInput} name="phone1" /> 
```

onChanged event is fired only onFocus and onBlur

**Comment by sanniassin** [comment]
@guilhermehubner You should omit `maxLength` prop. `react-input-mask` won't allow to enter anything longer than the mask length anyway.
