### ISSUE TITLE
how can i use this on rails?

### ISSUE THREAD

**Issue by towonzhou** [sanniassin/react-input-mask#13]
how can i use this on rails?

**Comment by sanniassin** [comment]
Look at react-rails – https://github.com/reactjs/react-rails

And it's better to use google, because i have no rails experience.

**Comment by drakmail** [comment]
I'm use it with ease – I just copied compiled source (https://github.com/sanniassin/react-input-mask/blob/master/InputElement.js) to my components directory, renamed `inputElement.js` to `inputElement.js.jsx` and removed `var React = require("react");` line.

PS. It works if [react-rails](https://github.com/reactjs/react-rails) correctly configured.

**Comment by towonzhou** [comment]
@drakmail nice, so good
