### ISSUE TITLE
beforeChange throws error and is never called

### ISSUE THREAD

**Issue by individual11** [sanniassin/react-input-mask#137]
Right now with your example code, I'm getting the following error in Chrome

```
Warning: React does not recognize the `beforeChange` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `beforechange` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Any ideas? I've checked and am using the correct version.

**Comment by rgripper** [comment]
I've just stumbled upon the same problem, haha! `beforeChange` has been added 11 days ago, but the latest release is from 3 months ago.

**Comment by sanniassin** [comment]
Yes, it's a feature of 2.0.0 which is not released yet. You can clone the repo and build it with `npm run build` or wait until I release a beta (within a week I hope).

**Comment by sanniassin** [comment]
Released a beta. You can try it with `npm i react-input-mask@next`.

Take a look on readme, because name and arguments of `beforeChange` have changed.
