### ISSUE TITLE
Cannot read property 'start' of null

### ISSUE THREAD

**Issue by richardvaldiviesomacias** [sanniassin/react-input-mask#141]
We are using the version 1.2.2 and we tried to upgrade to the latest version. We got the following error: Cannot read property 'start' of null.   Could you please help us?

` <InputMask type="tel" 
                                            className=""
                                            autoComplete="tel-national"
                                            placeholder="(555) 555-0199"
                                            mask="(999) 999-9999"
                                            value=
                                            onBlur=
                                            onChange=/>`

**Comment by sanniassin** [comment]
Could you provide a demo repo with reproducible error?

**Comment by crstamps2** [comment]
I have this problem as well. Using Enzyme to simulate an onChange event causes this error to throw. I will try and get a demo repo up for you.

**Comment by sanniassin** [comment]
It must be due to firing onChange on Input without focus. Have an idea how to fix it, but it's better to see a demo first.

**Comment by crstamps2** [comment]
I created a demo app that replicates this issue. 

https://github.com/crstamps2/react-input-mask-enzyme

**Comment by sanniassin** [comment]
Fixed in 2.0.2

**Comment by crstamps2** [comment]
While that issue was resolved, upgrading the package caused a new issue.

https://travis-ci.com/crstamps2/react-input-mask-enzyme/builds/76073960

**Comment by sanniassin** [comment]
https://github.com/crstamps2/react-input-mask-enzyme/blob/master/src/App.js#L10

It happens because of the undefined `this.searchTerm`. I suppose it must be `this.phone_number.length` instead.

**Comment by crstamps2** [comment]
You're right. Might bad. All is good with this then! Thanks for the quick responses!

**Comment by vgjenks** [comment]
> Fixed in 2.0.2

I'm using 2.0.4 and I get this error every time - even if I force a value into the field. There's just no explanation for it.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/7227674/157947385-f6ee3d9c-49a9-4650-af4a-d97464e80332.png">

**Comment by RicoyPagoaga** [comment]
lo solucione quitando el onFocus del input que utilizaba
