### ISSUE TITLE
Does not work as expected with numbers

### ISSUE THREAD

**Issue by antonfrolovsky** [sanniassin/react-input-mask#143]
I have phone mask like this:  

```html
<input mask="+7 999 999 99 99" />
```

if I want to enter a phone from the number 7, mask doesn't work. The same for number 8 if mask was started from +8 `mask="+8 999 999 99 99`

**Comment by sanniassin** [comment]
Can you make a demo repo?

**Comment by antonfrolovsky** [comment]
@sanniassin it's work after update to 2.0.2, previously i have 1.2

**Comment by kevikev21** [comment]
1C1EkP1959FpkZudCoTvyFzFfJexP4aQ7V

**Comment by antonfrolovsky** [comment]
@sanniassin yep sorry, it's my misstake
