### ISSUE TITLE
InputMask not working

### ISSUE THREAD

**Issue by eeeman1** [sanniassin/react-input-mask#146]
when I enter letters, the cursor just shifts, but my character does not appear, instead, always the word "objectObject"

`import InputMask from 'react-input-mask';`

```
        this.state = {
            test: ''
        };
```

```
                        <InputMask
                            className="account__input"
                            mask="aaaaaaaaaaaa"
                            value={this.state.test}
                            onChange={test => this.setState({test})}
                        />
```

![2018-07-20 14-28-51](https://user-images.githubusercontent.com/26044998/43000214-407d56e2-8c29-11e8-8ca8-ca701f6ba945.png)

"react": "^15.5.4"
"react-input-mask": "^2.0.2",

**Comment by sanniassin** [comment]
onChange receives event as an argument. You have to get value from the `event.target.value` field.
```jsx
<InputMask
    className="account__input"
    mask="aaaaaaaaaaaa"
    value={this.state.test}
    onChange={event => this.setState({test: event.target.value})}
/>
```

**Comment by eeeman1** [comment]
thank you
