### ISSUE TITLE
Chrome autofill values are removed

### ISSUE THREAD

**Issue by dcocchia** [sanniassin/react-input-mask#15]
Can be seen happening here: http://g.recordit.co/YQDzqaGKiu.gif

![yqdzqagkiu](https://cloud.githubusercontent.com/assets/1747661/11601473/4941e7b0-9a88-11e5-96b3-d392cf764835.gif)

**Comment by sanniassin** [comment]
You can get autofilled value before mask setup and use it with value or defaultValue property. Sometimes autofill may not fire change event, so it's better to set mask property to null, wait for first focus on input, get value directly from DOM node and then set mask property to your mask along with value.
