### ISSUE TITLE
Where's the changelog?

### ISSUE THREAD

**Issue by vfonic** [sanniassin/react-input-mask#150]
Hey! Thanks for the great package!
It really helped me.

I was just reading the documentation and I realized I could make a good use of `beforeMaskedValueChange`. I'm currently using `react-input-mask@1.2.2` where this method is not available. So I wanted to update to the latest version, but I don't see any upgrade/migration/changelog guide. What do you suggest would be the best approach to update the library?

Thanks!

**Comment by sanniassin** [comment]
You can find changelog at the [releases](https://github.com/sanniassin/react-input-mask/releases) page. In fact, there are no breaking changes in the version 2 unless you use React 0.13 or older, so you can safely upgrade.
