### ISSUE TITLE
Style for mask. Is it posible?

### ISSUE THREAD

**Issue by JKaminsky1988** [sanniassin/react-input-mask#151]
Hello!
I need to style mask for my input. If it posible, tell me pleas how)

**Comment by sanniassin** [comment]
@JKaminsky1988 Could you please explain what kind of styling you're talking about?

**Comment by komarnitskyi** [comment]
@sanniassin I think it's about something like a different color for `/` symbol in `99/99/9999` pattern. But it's impossible with input without some `hacks`

**Comment by anuj-datopic** [comment]
Any update on the styling? I am trying to use XXXX-XXXX as phone format mask and would like to show Xs as grey and the actual typed number as normal black.

**Comment by scarpeace** [comment]
Does anyone have a update on how to use styled components on the InputMasks?
