### ISSUE TITLE
Android input cursor bug

### ISSUE THREAD

**Issue by jordijansen** [sanniassin/react-input-mask#16]
Hi,

This component does not work as aspected on Android (Chrome on Galaxy S6 and Nexus 5). If I enter a character, the character will be added but then the input cursor will jump to the start of the input. So if I type a seccond character it will be placed in front of the first character.

I use the component with the following settings: 
mask: \*\*\*\* \*\*\*\* \*\*\*\* \*\*\*\*
maskchar: null

**Comment by sanniassin** [comment]
Which versions of Android, Chrome and react-input-mask has been used?

**Comment by jordijansen** [comment]
Android 5.1.1 and Android 6.0.1
Chrome: 47.0.2526.83

**Comment by sanniassin** [comment]
Thanks, should be fixed in 0.5.7. Please comment if it works or not.

**Comment by jordijansen** [comment]
I can indeed confirm it is now properly working. Thanks! This issues can now be closed.
