### ISSUE TITLE
No reverse option

### ISSUE THREAD

**Issue by luanpotter** [sanniassin/react-input-mask#17]
It would be nice to have a reverse option, that would make the mask be applied right to left.
So one could use a mask for money, for example, '999,999,999.99' and it would work no matter the amount of digits.

**Comment by sanniassin** [comment]
It's pretty hard to implement it quickly and this option is more about formatting, not masking and can be done with regex inside input onChange handler. Look at [StackOverflow question](http://stackoverflow.com/questions/2254185/regular-expression-for-formatting-numbers-in-javascript).

I trying to keep component as simple as possible, so won't implement that at this moment.

**Comment by livimonte** [comment]
It's not the best option to use 2 different plugins for the same thing, but this one is specific to handle money, very simple and works well: https://github.com/jsillitoe/react-currency-input
