### ISSUE TITLE
input[type="number"] not supported in chrome

### ISSUE THREAD

**Issue by kpaxqin** [sanniassin/react-input-mask#18]
Browser: Chrome 47

When I'm working with input[type="number"], I got the following error messages in my console:
>Uncaught InvalidStateError: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.

I know that input[type="number"] does not support the "selectionStart" property and I've noticed that we've handled it in the code:

```js
if ("selectionStart" in input && "selectionEnd" in input) {
            input.selectionStart = start;
            input.selectionEnd = end;
} else {
//...
}
```
but currently in Chrome , it's not enough because `"selectionStart" in input` will return true even the input is number field. and when we try to visit the "selectionStart" property, we'll get an error;

**Comment by sanniassin** [comment]
Could you describe your use case and what kind of mask used? Because numeric inputs has [very limited range of allowed characters](http://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in) it could be hard to make a meaningful mask.

**Comment by kpaxqin** [comment]
@sanniassin 
we use mask on a numeric input to limit the max-length of user input. We have validations of input length, but it will be better user-experience to prevent user from input extra things
