### ISSUE TITLE
Input mask for name 

### ISSUE THREAD

**Issue by Hakawa2** [sanniassin/react-input-mask#180]
Hi sorry for my bad english k k k.

I would like to know how to mask for input only accept letters.
utilise only mask =' a ' ?

**Comment by Hakawa2** [comment]
Hi sorry for my bad english k k k.

I would like to know how to mask for input only accept letters.
utilise only mask =' a ' ?

**Comment by annezao** [comment]
> Hi sorry for my bad english k k k.
> 
> I would like to know how to mask for input only accept letters.
> utilise only mask =' a ' ?

Why did you close it? I wanted to know :(
