### ISSUE TITLE
Array of RegExp masks not working?

### ISSUE THREAD

**Issue by reintroducing** [sanniassin/react-input-mask#197]
I'm trying a very simple RegExp set of masks and its not working, I can type anything in the field:
```js
<InputMask
    mask={[/^([0-2])/, /([0-9])/, ':', /[0-5]/, /[0-9]/]}
/>
```
Any idea why this would be happening? It seems like this should be correct according to the docs. Thanks.

**Comment by lexkomlev** [comment]
Same problem.
I tried to use cyrillic symbols in mask, and it's not working too
`<InputMask
    mask={[/[а-я]/i, /а-я/i, ' ', /[0-9]/, /0-9/]}
>`

**Comment by kfpo** [comment]
I'm not sure that it's even implemented, looking at the code:
https://github.com/sanniassin/react-input-mask/blob/0f7e538a911feaa7a101c2ffcd8868eaf6a5ace5/src/utils/parse-mask.js#L37
Not sure why it's in README though.

**Comment by demkovych** [comment]
What version of react-input-mask you are using? It works with **3.0.0-alpha.0**

**Comment by reintroducing** [comment]
@demkovych Ah, we are using 2.0.4. Is this a 3.x+ feature? I didn't realize 3.x was out, I was just pulling in what npm had which is still 2.0.4.

**Comment by reintroducing** [comment]
Well, I realized I was using 2.x and the master README is for 3.x. 2.x only uses strings for masks. @sanniassin should probably update the README in master saying that these docs are for 3.x since `npm install` still installs 2.x, which makes this quite confusing.

**Comment by reintroducing** [comment]
Disregard my comment above, it actually is mentioned in the readme and i just didn't read it. I guess what I was trying to say is that master should match what `npm install` will give a user to avoid confusion :)

**Comment by vanikalai** [comment]
I have update the version to 3.00-alpha.0 but still its not working
Actually I am facing the issue like onchange is not with Input MasK
