### ISSUE TITLE
Incorrect README about maskChar

### ISSUE THREAD

**Issue by Cherkasik** [sanniassin/react-input-mask#203]
Property maskChar, that is working, called maskPlaceholder in documentation.
It would be better to update documentation for not confusing other people who wants to use this library.

**Comment by GBarkhatov** [comment]
@Cherkasik I've encountered this also.
Please use "3.0.0-alpha.0" via "yarn add react-input-mask@3.0.0-alpha.0", as the default behavior is to install "latest" from npm. Which is 2.0.4

https://i.imgur.com/usqjZKv.png

**Comment by GBarkhatov** [comment]
Also, maskChar and maskPlaceholder are different things

**Comment by Cherkasik** [comment]
Hmmm dev branch on master... Strange but whatever

**Comment by GBarkhatov** [comment]
@Cherkasik this is how all these JS libraries are done currently 😎Chaotic
