### ISSUE TITLE
3.0.0-alpha.1 show up in `npm outdated`

### ISSUE THREAD

**Issue by ptgamr** [sanniassin/react-input-mask#204]
Just noticed this today while doing the upgrade for my project deps. 

<img width="1011" alt="Screen Shot 2020-01-21 at 12 34 44 PM" src="https://user-images.githubusercontent.com/1619740/72763910-b29b7380-3c4a-11ea-982c-88ae092641b7.png">

Is this an intended release? After upgrading from v2, everything is broken, and I couldn't find a migration guide anywhere. I'm a heavy user of v2 `formatChars` props and seems like it's not available in v3.

**Comment by sanniassin** [comment]
Thank you for the report! I mistakenly published alpha build under the `latest` tag. Reverted `latest` back to `2.0.4`.
