### ISSUE TITLE
isPositionEditable Issue on Production

### ISSUE THREAD

**Issue by alvnrapada** [sanniassin/react-input-mask#213]
I'm encountering this error on my production env, and i can't find any issues regarding this, in my dev env it's working fine. Thanks in advance.

<img width="1266" alt="Screen Shot 2020-03-18 at 9 39 42 PM" src="https://user-images.githubusercontent.com/62341430/76966991-c0772780-6961-11ea-8c41-ab26b9c521dc.png">

**Comment by arracos** [comment]
I'm seeing this issue as well.  With **3.0.0-alpha.2**.  It works locally but not when deployed live site.

Update:
I found that **3.0.0-alpha.0** does not throw the error in my specific use case.  Some kind of issue with the dependency on react-dom (given the error this throws)?

**Comment by alvnrapada** [comment]
Fix this by changing package 😂
