### ISSUE TITLE
Length property

### ISSUE THREAD

**Issue by davidflores2** [sanniassin/react-input-mask#23]
When using this component, my inputs have always the same length. For example, if I mask a DOB input and do 99/99/9999 - and then do dob.length the result will be 10 even when the input is empty. Is this the intended behavior?
It would work best for me if this didn't happen.

**Comment by Abhijeetjaiswalit** [comment]
getting same issue.

**Comment by sanniassin** [comment]
Not a bug. onChange triggers on any value change so usually your value equals to what you see in input. If you have an empty input and set focus on it you'll see a placeholder `__/__/____` and it's length is 10.

You can set `maskChar` property to `null` if you want to disable placeholder.

**Comment by Abhijeetjaiswalit** [comment]
@sanniassin  so you are saying every masked input works in same fashion? i.e, the maskchar placeholders works like a real input on focus, not just a dummy placeholders? In my case i have to show default 0's as maskchar, and I fixed the minLength of field 16 and maskChar="0" . Now if user enters 2 or 3 digit only, the length validates.
