### ISSUE TITLE
I pass props.value but Input do not work correct

### ISSUE THREAD

**Issue by coldSeattle** [sanniassin/react-input-mask#233]
I have an mask like: +7 ___ ___ __ __
and I want to set initial value from props like +7 499 ___ __ __
but also I cannot then delete those digits, like ghosts. when type backspace arrow should moving  but bypass this props value

**Comment by SivaGanesh56** [comment]
any update ?

**Comment by coldSeattle** [comment]
I already a long time did not usein this library and I think I should close this issue.
