### ISSUE TITLE
Error when using in props inputRef instead just ref attribute

### ISSUE THREAD

**Issue by coldSeattle** [sanniassin/react-input-mask#234]
Warning: React does not recognize the `inputRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
![Снимок экрана 2020-08-31 в 18 02 14](https://user-images.githubusercontent.com/56102448/91734868-25db6f80-ebb4-11ea-8931-677beb051286.png)

**Comment by coldSeattle** [comment]
version will be 2.0.4 for correct work

**Comment by vhunko** [comment]
it seems like this issue is relevant again in version 3.0.0-alpha.2
getting `Warning: React does not recognize the `inputRef` prop on a DOM element.`
