### ISSUE TITLE
when passing props value with "_", it saved in value

### ISSUE THREAD

**Issue by coldSeattle** [sanniassin/react-input-mask#235]
passing:
![Снимок экрана 2020-09-01 в 10 34 30](https://user-images.githubusercontent.com/56102448/91820247-bc547300-ec3e-11ea-8030-1f97f2be5702.png)

Expected: +7 784 433 __ __

Received:
![Снимок экрана 2020-09-01 в 10 35 59](https://user-images.githubusercontent.com/56102448/91820662-f0c82f00-ec3e-11ea-9579-b9ef32de4fe6.png)

**Comment by mathlimma** [comment]
export interface MaskOptions {
  mask: string | Array<(string | RegExp)>;
  maskChar: string;
  alwaysShowMask: boolean;
  formatChars: Record<string, string>;
  permanents: number[];
}

apparently they changed the props, if you pass  `maskChar="" ` it  will work

**Comment by coldSeattle** [comment]
Thanks!
