### ISSUE TITLE
react-input-mask: children must be a function

### ISSUE THREAD

**Issue by criscordovaa** [sanniassin/react-input-mask#248]

**Comment by Darth-koder007** [comment]
I see this issue was close, unfortunately I am still facing it. What was the resolution behind closing this, if i may ask ?

**Comment by SerhiyDemchuk** [comment]
@Darth-koder007 

                                <InputMask
                                    mask = '(999)-999-9999'
                                    maxLength = '10'>
                                    {(inputProps) => (
                                        <YourInputComponent
                                            { ...inputProps }
                       
                                        />
                                    )}
                                </InputMask>
