### ISSUE TITLE
Unmasked input value

### ISSUE THREAD

**Issue by drakmail** [sanniassin/react-input-mask#25]
Does there any ways to get unmasked input value? For example, with mask `+7 (999) 999-99-99` in `onChange` event value of `event.target.value` variable is `+7 (111) 123-12-12`. Could I get just `1111231212`?

**Comment by istarkov** [comment]
Are you a programmer? This can be done in just one line of your code.

**Comment by drakmail** [comment]
:-) Already did it, but many jQuery-based libraries provide methods to get unmasked value and I think that it's just more comfortable way

**Comment by istarkov** [comment]
:-) IMHO in reality 99% users of this library need masked result, other 1% could write simple transform. Otherwise just this simple step needs internally additional property or other compinent interface changes. As a result you will get a new jquery ui, as other user will ask this component to support combobox suggestions, etc. The idea is to be small and simple as possible.

**Comment by drakmail** [comment]
Agreed

**Comment by pudgereyem** [comment]
Hi! I'd also like to access the unmasked value.
Wouldn't it be neat to store the unmasked (clean) value as well? This way we could access the clean value instead of writing transforms.

@istarkov I read your comment. I'm not sure if the users of this library need the masked or unmasked value. In our case I need to send the unmasked value to the server. 

Ping @sanniassin @drakmail

**Comment by Sorcer23** [comment]
you can do something like this:
const input = this.refs.YourInputMaskNode;
input.getInputValue().slice(input.maskOptions.prefix.length);

**Comment by CarlBurdick** [comment]
@istarkov Really? I thought the whole point of input masking was user experience. Why would you want to send unnecessary static characters to the server or store them in the database?

**Comment by istarkov** [comment]
Yes, its much more better to add few (not few if you support international formats) kbs of formatting code to every client of your db. Lets stop using json - it has enormous amount of unnecessary static characters vs C structs. Lets put every edge case into every library in the world to make ux 100%.

**Comment by lolenko** [comment]
this component doesnt make sense if it couldn't provide unmasked value

**Comment by kauly** [comment]
To unmask the value, before send to the server,  you can do something like that:

`const unmask = value.replace(/[^\d]/g, '');`

**Comment by MarcusBondezan** [comment]
Yes ... there is a use case for it. Imagine that your UX guy/girl asks you to present the form fields with mask because it improves user experience. Now imagine that you need to send that data to an API which only accepts values without the mask characters.
Off course you can handle the the transforming by yourself, it's not even hard to do it. Some mask libs have this functionality and I think this is very welcome.

**Comment by cristoferrao** [comment]
ya it should give unmasked value in jquery there is coming similar which I had used once 


```
            $("#expiryDatetxt").inputmask("99/99/9999");
            $("#expiryDatetxt").focus(function () {
                $(this).inputmask("99/99/9999");
            });
            $("#expiryDatetxt").blur(function () {
                let exDate = this.inputmask.unmaskedvalue();
 
             ///   $(this).val(valueToPass);/// send this to server end got it as 12022021

            }); 
```

**Comment by FranklynSeabraOSF** [comment]
I thought masks should only be in the visual...

**Comment by WalissonPires** [comment]
My solution:

```typescript
import React, { Component, useState } from 'react';
import { render } from 'react-dom';
import InputMaskRect, { Props as InputMaskRectProps } from "react-input-mask";
import './style.css';

type Data = {
  zipecode: string;
  date: string;
}

const App = () => {

  const [ data, setData ] = useState<Data>({ zipecode: '', date: '' });

  const handleChangeZipCode = (unmaskedValue: string, event: React.ChangeEvent) => {

    setData({
      ...data,
      zipecode: unmaskedValue
    });
  };

  const handleChangeDate = (unmaskedValue: string, event: React.ChangeEvent) => {

    setData({
      ...data,
      date: unmaskedValue
    });
  };

  const handleSubmit = (event: React.FormEventHandle<HTMLFormElement>) => {

    event.preventDefault();
    alert(JSON.stringify(data));
  }

  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label>ZipCode</label>
        <MyReactInputMask value={data.zipecode} mask="99.999-999" onChange={handleChangeZipCode} />
      </div>
      <div>
        <label>Date</label>
        <MyReactInputMask value={data.date} mask="99/99/9999" preserveMask onChange={handleChangeDate} maskPlaceholder="_" />
      </div>
      <button>Submit</button>
    </form>
  )
}


type MyReactInputMaskProps = Omit<InputMaskRectProps, 'onChange'> & {
  preserveMask?: boolean;
  onChange: (unmaskedValue: string, event: React.ChangeEvent<HTMLInputElement>) => void;
}

const MyReactInputMask = ({ mask, value, maskPlaceholder, preserveMask, onChange, maxLength, ...props }: MyReactInputMaskProps) => {

  const maskChar = maskPlaceholder || (props as any).maskChar || '_';

  const unmaskValue = (value: string) => {

      let unmaskedValue = '';
      for(let i = 0; i < value.length; i++) {

          const isValueChar = mask[i] === '9' || mask[i] === 'a' || mask[i] === '*';
          const isMaskChar = value[i] === maskChar;

          if ((isValueChar || preserveMask) && !isMaskChar)
              unmaskedValue += value[i];
      }

      return unmaskedValue;
  }

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {

      const value = unmaskValue(event.target.value);
      onChange(value, event);
  }

  return <InputMaskRect mask={mask} value={value} onChange={handleChange} {...{maskChar: maskChar}} {...props} />;
}


render(<App />, document.getElementById('root'));

```

https://stackblitz.com/edit/react-ts-whl5ca?file=index.tsx

**Comment by coderbahrom** [comment]
> To unmask the value, before send to the server, you can do something like that:
> 
> `const unmask = value.replace(/[^\d]/g, '');`

What I am searching thanks

**Comment by skillwork-mdimitrov** [comment]
> To unmask the value, before send to the server, you can do something like that:
> 
> `const unmask = value.replace(/[^\d]/g, '');`

Thanks my man <3

P.S. Huge miss on the lib side for not providing such behavior by default. Surely the Back-end would want unmasked values..

**Comment by waghcwb** [comment]
> To unmask the value, before send to the server, you can do something like that:
> 
> `const unmask = value.replace(/[^\d]/g, '');`

We can simplify even more by:
```js 
let unmasked = value.replace(/\D/g, '')
```

But this only works if you're not using `maskChar` with a numeric value, eg: `maskChar={'0'}`.

@sanniassin 
That's why we need an `unmasked` value..

**Comment by FabioDavidF** [comment]
Chiming in my 2 cents as a user of the library: I expect masks to be only aesthetic, and to not actually change the input's value. And not having a built-in way of extracting the raw data from the masked input seems like such a missed core part of the feature.

**Comment by MudulOzan** [comment]
> Chiming in my 2 cents as a user of the library: I expect masks to be only aesthetic, and to not actually change the input's value. And not having a built-in way of extracting the raw data from the masked input seems like such a missed core part of the feature.

this!!! couldn't agree more
