### ISSUE TITLE
is there a library with the same features, but for react native ?

### ISSUE THREAD

**Issue by coldSeattle** [sanniassin/react-input-mask#251]
is there a library with the same features, but for react native ?
or I can use that library in react native expo app too ?

**Comment by JeanMonteiro** [comment]
https://www.google.com/search?q=react-native-masked-text&oq=react+native+text&aqs=chrome.2.69i57j35i39l2j0i67l2j0j69i60l2.5949j0j7&sourceid=chrome&ie=UTF-8

**Comment by JeanMonteiro** [comment]
https://github.com/benhurott/react-native-masked-text

this one is good!

**Comment by coldSeattle** [comment]
thanks!!!

**Comment by coldSeattle** [comment]
thanks for research!!!
