### ISSUE TITLE
Tags on versioned commits

### ISSUE THREAD

**Issue by piranha** [sanniassin/react-input-mask#26]
It would be nice to have some tags in repository so it'll be possible to download exactly version 0.5.10 without resorting to referring to a commit hash.

Like `https://github.com/sanniassin/react-input-mask/blob/0.5.10/InputElement.js`

**Comment by sanniassin** [comment]
@piranha Added tag for 0.5.10 and will try to not forget about it in future versions :)

**Comment by piranha** [comment]
Thanks! :)
