### ISSUE TITLE
Given example program not working

### ISSUE THREAD

**Issue by mk48** [sanniassin/react-input-mask#269]
The given example in the Readme.md file seems not working.
I have included a code sandbox link. 

**Below is the document example**
![image](https://user-images.githubusercontent.com/3082469/131861627-aba65455-b42f-4bc4-9443-875350c4f747.png)

**Code sandbox screen**
![image](https://user-images.githubusercontent.com/3082469/131861808-04b64946-9e25-4d71-ba2b-413dafe06fba.png)

**Full code**
```
import React, { useState } from "react";
import InputMask from "react-input-mask";

const firstLetter = /(?!.*[DFIOQU])[A-VXY]/i;
const letter = /(?!.*[DFIOQU])[A-Z]/i;
const digit = /[0-9]/;
const msk = [firstLetter, digit, letter, " ", digit, letter, digit];

const Txt = () => {
  const [value, setValue] = useState<string>("");
  const onChange = (e: any) => {
    setValue(e.target.value);
    //console.log(e);
  };
  return (
    <InputMask
      mask={msk}
      onChange={onChange}
      value={value}
      alwaysShowMask={true}
    />
  );
};

export default Txt;
```

**Code sandbox link**
https://codesandbox.io/s/input-mask-uwduh?file=/src/Txt.tsx:0-575

Am I missing anything?

**Comment by TimofeiKurohtin** [comment]
It only works with the version 3.0.0-alpha.0, consider checking your version

**Comment by mk48** [comment]
Thanks, it's working in the  3.0.0-alpha.0
