### ISSUE TITLE
char is a reserved word

### ISSUE THREAD

**Issue by piranha** [sanniassin/react-input-mask#28]
Hi, I'm not sure how welcoming you will be toward change like that, but I'm trying to use react-input-mask in a ClojureScript project and because of that I'm using Google Closure Compiler. 

Which complains that `char` is a reserved keyword. What do you think about changing that name to a different one? :)

**Comment by sanniassin** [comment]
@piranha Damn, they've reserved a lot of good words :) Could be done if it's not a harmless warning and really affects something.

**Comment by piranha** [comment]
They did! :( It actually prevents minification completely, so I can't get react-input-mask minified now. :)

What do you think about using `ch` instead of `char`? I'd like to submit pull request, but not sure about naming.

**Comment by sanniassin** [comment]
@piranha Ok, changed to "character" in 0.6.2

**Comment by piranha** [comment]
Thanks!

**Comment by piranha** [comment]
Sorry for nagging, can you please update build file? :)

**Comment by sanniassin** [comment]
Sure. Updated build and release to reflect build commit.
