### ISSUE TITLE
Using maskChar instead of maskPlaceholder

### ISSUE THREAD

**Issue by chiralium** [sanniassin/react-input-mask#283]
![image](https://user-images.githubusercontent.com/61596633/158072865-8b466ac8-153a-4f5e-b035-c77edc6c2ed1.png)

index.d.ts having maskPlaceholder, but  real prop name is maskChar, so I should use the ts-ignore to change default mask placeholder char

![image](https://user-images.githubusercontent.com/61596633/158072913-f7349f2c-0f64-479c-ad6a-e83ebab0a1f7.png)

**Comment by ailchenkoDynamo** [comment]
you are using different versions of main package and package with types

**Comment by chiralium** [comment]
> you are using different versions of main package and package with types

ok, this make sense. thank you for your reply.
