### ISSUE TITLE
On Windows Phone, characters show up twice

### ISSUE THREAD

**Issue by cebiggs** [sanniassin/react-input-mask#29]
Hi,

We are using react-input-mask in a webapp and it's worked great so far. But we've recently realized that the mask is causing problems on Windows phones (which we do have to support, unfortunately).

Steps to reproduce:

1. Get a Windows 10 Phone with the Edge Browser (we are testing on a Lumia 950, Microsoft Edge 25.10586.107.0)
2. Go to the demo page: http://sanniassin.github.io/react-input-mask/demo.html
3. Try to type in any of the examples.
4. For every character you type, it shows up twice:

Example: I type `1` into the input element. It actually shows `11`.

We do not really understand why this is happening, but know that if we disable the `onKeyPress` event handler inside `InputElement`, the bug stops happening (when mask character is undefined).

We are hoping you can fix this so we don't have to fork and just put in our bad hack :(

Thank you!

**Comment by istarkov** [comment]
Are you really think that developer of free open source library will get somewhere one of the most unpopular phone and platform?
I think as you have access to such device the minimal thing you can do is just provide a PR to this library with a fix or a solution how to get this bug without Lumia etc...

**Comment by istarkov** [comment]
The best issue is a PR, thank you @cebiggs ;-)

**Comment by sanniassin** [comment]
@cebiggs Thank you for investigation. Fixed in 28e2294, please report if anything else is broken on Windows Phone.

@istarkov Thank you too :) Actually i'm able to debug it with WP emulator on Windows 10 which runs on virtual machine itself, but nested virtualization makes my laptop cry.
