### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by 0xLDev** [sanniassin/react-input-mask#311]
Using react 18.0.1 and ant design 4.20 library get this error
![image](https://user-images.githubusercontent.com/67437278/234504902-e71cbe0a-e6bb-4b02-8785-893839df86d4.png)

**Comment by alexhrtm** [comment]
Did you find any solution?

**Comment by alexandrehrt** [comment]
Did you find any solution?

**Comment by 0xLDev** [comment]
> Did you find any solution?

Found, used other library antd-mask-input
