### ISSUE TITLE
React 0.15

### ISSUE THREAD

**Issue by mmakarin** [sanniassin/react-input-mask#35]
Hello. Can you update react peer dependency to ```"react": "^0.14.0 || ^15.0.0-0"```?

**Comment by sanniassin** [comment]
@mmakarin What's wrong with current one ("react": ">=0.12.0")? It's compatible with 15.0.0 too.

**Comment by mmakarin** [comment]
npm complains

**Comment by sanniassin** [comment]
@mmakarin Can you provide logs and your package.json?

**Comment by mmakarin** [comment]
It's another library's fault. I'm sorry.
