### ISSUE TITLE
Chrome@Android 5.1: Invalid output

### ISSUE THREAD

**Issue by CezaryDanielNowak** [sanniassin/react-input-mask#36]
Following input: `<MaskedInput mask="+1 (999) 999-9999" onChange={this.setValue}>`
This works fine for all browsers but Android browser:
Instead `+1 (440) 494-6237` value is set to: `+1 (440) 494-6237_`

**Comment by sanniassin** [comment]
@CezaryDanielNowak Can't reproduce. Can you fork this example, modify it to make this issue appear and provide step by step instructions to reproduce it?

Is it Chrome or Android browser? They are not same.

**Comment by CezaryDanielNowak** [comment]
Hmm.. I cannot reproduce it as well, when it's separated from my App... I think, we can close the issue for now. I'll post update if find the reason in the future.

**Comment by sanniassin** [comment]
@CezaryDanielNowak Sorry, i've missed link to example – http://codepen.io/sanniassin/pen/dMdaRj
