### ISSUE TITLE
When input type is number masking breaks

### ISSUE THREAD

**Issue by reintroducing** [sanniassin/react-input-mask#37]
Hello,
I know there was an issue open similar to this and is now closed but I wanted to show the use case for this.  I'm testing on a mobile device (in this case in the iOS simulator) and my mask is for a credit card set to '9999 9999 9999 9999'.  I'm setting the type to number because I want the numbers to be visible on the iOS keyboard when I go to input the credit card number.  Here is a short video of the behavior:

http://screencast.com/t/cajgTxrzP

Also worth noting if I remove the spaces from my mask it works as expected.  If I replaced the spaces with dashes it doesn't work either.

If I change the type to tel everything works as expected and yes, that does bring up a number only keyboard, but for some reason it feels weird to me that I should have to do that.  

Thoughts?

**Comment by sanniassin** [comment]
@reintroducing It is weird to use number type too because it was designed for actual numbers, not for set of digits. That's why browser restricts input to very limited set. Can't override that with js, so you have to use tel anyway.
