### ISSUE TITLE
getDOMNode is deprecated

### ISSUE THREAD

**Issue by nikshulipa** [sanniassin/react-input-mask#4]
Trying to use this lib with react v0.14.0-beta2 getting this error in console:
`Warning: InputElement.getDOMNode(...) is deprecated.  Please use React.findDOMNode(instance) instead.`

Stacktrace is 
```
warning	@	warning.js:45
ReactBrowserComponentMixin.getDOMNode	@	ReactBrowserComponentMixin.js:30
setCaretPos	@	InputElement.js:223
setCaretToEnd	@	InputElement.js:164
.....
```

Could you, please, fix it?

**Comment by sanniassin** [comment]
Fixed
