### ISSUE TITLE
Component do not work in WinPhone.

### ISSUE THREAD

**Issue by andalt** [sanniassin/react-input-mask#40]
I set mask "99.99.9999" and only first digit is allowed.

**Comment by sanniassin** [comment]
@andalt It works for me. Really.

Seriously, can you provide more information? WinPhone OS and browser versions, react-input-mask version. Is demo page (http://sanniassin.github.io/react-input-mask/demo.html) works? Sample of your code?

**Comment by andalt** [comment]
@sanniassin I'm shocked. Nokia Lumia 620 (Windows 8.1), Nokia Lumia 730 (Windows 8.1), Nokia Lumia 930 (Windows 10), Nokia Lumia 1520 (Windows 8.1) - works.Microsoft Lumia 640 (Windows 8.1) - not work.

**Comment by sanniassin** [comment]
@andalt Interesting, but i have Windows Phone emulators only and can't reproduce and resolve this issue. Can you investigate it and make a PR?

**Comment by axelson** [comment]
@andalt does this cause any sort of javascript error to be thrown?
