### ISSUE TITLE
ref doesn't get set for InputElement

### ISSUE THREAD

**Issue by netpoetica** [sanniassin/react-input-mask#43]
If you have a React component like:

```
import InputElement from 'react-input-mask';

//...
render() {
        return (<InputElement
          ref='fieldInput'
        />);
}
```

And then try to reference this.refs.fieldInput, it will not be defined. If you take the exact same code and turn it into a plain old input, it will work:

```
//...
render() {
        return (<input
          ref='fieldInput'
        />);
}
```

Is this by design?

**Comment by sanniassin** [comment]
@netpoetica It's defined but it will point to ReactComponent while plain input will point to input DOM node, so you have to use ```ReactDOM.findDOMNode(this.refs.fieldInput)``` to get same result.

**Comment by netpoetica** [comment]
Thank you, you're right :-) good catch!
