### ISSUE TITLE
Support Unknown Legnths of Characters

### ISSUE THREAD

**Issue by netpoetica** [sanniassin/react-input-mask#44]
I was attempting to use this to input mask an email address, but it doesn't seem like such a thing would be possible with this library.

For example, I would think something like:
```
mask="*@*.a"
```
Should be able to support `firstname@mysite.com` or even `firstname.lastname@gmail.com`, etc. Is there not a way to support variable lengths of characters while input-masking? Maybe some syntax like:
```
mask="*...@*...\.a..."
```
would make sense?

**Comment by sanniassin** [comment]
@netpoetica No plans to implement this feature. And i doubt if it makes sense to solve email input filtering with masks.

**Comment by glauberramos** [comment]
This feature would be usefull for masks like currency
Brazilian Reais:
R$ 100.200,20
R$ 1.000,20
R$ 10,20
