### ISSUE TITLE
incompatible with IE

### ISSUE THREAD

**Issue by Zara603** [sanniassin/react-input-mask#48]
I had to remove the library as it was not compatible with IE 11. :-(

**Comment by sanniassin** [comment]
@Zara603 It works for me, so please provide more details:
- OS version
- react-input-mask version
- Sample of code which fails in IE
- More informative description. What doesn't works in IE and works in other browsers?

**Comment by Zara603** [comment]
import React, { Component, PropTypes } from 'react';
import _ from 'underscore'
import moment from 'moment'
import FontAwesome from 'react-fontawesome'
import { Row, Col, Input, OverlayTrigger, Popover } from 'react-bootstrap'
import InputElement from 'react-input-mask'
import Address from '../checkout/address'
import Summary from '../checkout/summary'
import * as CheckoutActions from "../../actions/checkout";
import {
  API_PLACE_ORDER_URL
} from '../../constants';


export default class Payment extends Component {

  constructor(props) {
    super(props);
    this.handleFieldUpdate = this.handleFieldUpdate.bind(this)
    this.validateFields = this.validateFields.bind(this)
    this.handleFormSubmit = this.handleFormSubmit.bind(this)
    this.onSubmit = this.onSubmit.bind(this)
    this.onPaypalSubmit = this.onPaypalSubmit.bind(this)
    this.handlePrevPage = this.handlePrevPage.bind(this)
    this.handlePopoverClick = this.handlePopoverClick.bind(this)
    this.calculateAvailableYears = this.calculateAvailableYears.bind(this)
    this.calculateAvailableMonths = this.calculateAvailableMonths.bind(this)

    this.state = {
      cardType : null,
      months: this.calculateAvailableMonths(),
      years: this.calculateAvailableYears(),
      formDetails: "",
      disabledPaymentBtn: false
    }
  }

  componentDidMount() {
    const self = this;

    $('#creditCard').validateCreditCard(function(result) {

      let cardLogo = null;
      let cardType = null;

      if (result.card_type) {
        switch (result.card_type.name) {
          case 'mastercard':
            cardLogo = '/public/build/images/cc-master-card.png'
            cardType = '002'
            break;
          case 'visa':
            cardLogo = '/public/build/images/cc-visa-card.png'
            cardType = '001'
            break;
          default:
            break;
        }
      }

      const { dispatch } = self.props;
      dispatch(CheckoutActions.updatePaymentField($(this).prop('name'), $(this).val()));
      dispatch(CheckoutActions.updatePaymentField("cardType", cardType));

      self.setState({
        cardLogo,
        cardType,
        luhnValid: result.luhn_valid,
        lengthValid: result.length_valid
      })
    })
  }

  calculateAvailableYears() {
    const yearsNum = 10

    let options = _(yearsNum).times((n) => {
      let tmpDate = moment().add(n, 'years')
      return tmpDate.format("YYYY")
    })

    return options
  }

  calculateAvailableMonths() {
    const monthsNum = 12

    let options = _(monthsNum).times((n) => {
      const valueTmp = (n + 1) < 10 ? "0" + (n + 1) : n + 1
      return {value: valueTmp, disabled: false}
    })

    return options
  }

  validateFields() {
    const validForm = $(this.refs.paymentForm).parsley().isValid()

    if (validForm) {
      this.props.dispatch(CheckoutActions.updatePaymentValid(true))
      this.onSubmit()
    } else {
      this.props.dispatch(CheckoutActions.updatePaymentValid(false))
      NOTIFICATION_CENTER.addNotification({message: "Please, check all the input fields", status: "error"})
    }
  }

  handleFieldUpdate(e) {
    if (e.target.name == "expireYear") {
      const currentYear = moment().format("YYYY")
      // Disable past months
      if (e.target.value == currentYear) {
        const currentMonth = parseInt(moment().format("MM"))

        let enabledMonths = _.map(this.state.months, (month) => {
          const monthTmp = month
          if (parseInt(month.value) <= currentMonth) {
            monthTmp.disabled = true
          }
          return monthTmp
        })

        this.setState({
          months: enabledMonths
        })
      } else {
        this.setState({
          months: this.calculateAvailableMonths()
        })
      }
    }

    this.props.dispatch(CheckoutActions.updatePaymentField(e.target.name, e.target.value))
  }

  handleFormSubmit(details) {
    let { billing, shipping} = this.props,
        billingAddress = this.props.isShippingDifferent ? billing : _.clone(shipping)

    billingAddress.addressType = 'Billing'
    shipping.addressType = 'Shipping'

    let finalDetails = {
      addresses: [billingAddress, shipping],
      isPayPal: details.isPayPal
    }

    if (_.has(details, "payment")) {
      finalDetails.payment = details.payment
    }

    this.setState({
      formDetails: JSON.stringify(finalDetails),
      disabledPaymentBtn: true
    })

    // this.props.dispatch(CheckoutActions.placeOrder(addresses))
  }

  componentDidUpdate() {
    if (this.state.formDetails) {
      $(this.refs.finalPaymentForm).submit()
    }
  }

  onSubmit() {
    const { isPaymentValid, securityCode, cardHolderName, cardNo, expireMonth, expireYear, cardType  } = this.props
    let details = {},
        payment = {}

    payment = Object.assign({}, payment, {
      cardHolderName,
      cardNo,
      securityCode,
      expireMonth,
      expireYear,
      cardType
    })

    details.payment = payment
    details.isPayPal = false

    if (cardType) {
      this.handleFormSubmit(details)
    } else {
      NOTIFICATION_CENTER.addNotification({message: "Please, check your credit card type", status: "error"})
    }

    // window.scroll(0, 0)
  }

  onPaypalSubmit(e) {
    const details = {isPayPal: true}
    this.handleFormSubmit(details)
  }

  handlePrevPage(e) {
    const { dispatch } = this.props;
    dispatch(CheckoutActions.updateCheckoutPage(2));
  }

  handlePopoverClick() {
    const isOverlayShown = this.refs.overlayCcvPopover ? this.refs.overlayCcvPopover.state.isOverlayShown : false

    this.setState({
      visiblePopover: isOverlayShown
    })
  }

  render() {
    const { method, billing, shipping, shippingTotal, securityCode, cardHolderName, cardNo, products, cardType } = this.props,
          expireMonth = this.props.expireMonth || "",
          expireYear = this.props.expireYear || ""

    let cvvPopover = <Popover
                    id="cvvPopover"
                    className="cvvPopover"
                    >
                      The CVV Number ("Card Verification Value") on your credit card or debit card is a 3 digit number on VISA®, MasterCard® and Discover® branded credit and debit cards.
                  </Popover>

    return (
      <div className="Checkout-payment">
        <h3 className="heading-italic hidden-md hidden-lg">Payment</h3>
          <div className="Checkout-content u-boxShadowMid">
            <Row>
              <Col xs={12}>
                <Row>
                  <Col xs={12} md={5}>
                    <div className="Checkout-paymentTab">
                      <p className="Checkout-instruction">Pay With Credit Card</p>
                    </div>
                  </Col>
                  <Col xs={12} md={2}>
                    <div className="Checkout-paymentOption u-lineThrough hidden-md hidden-lg"><span>OR</span></div>
                    <div className="Checkout-paymentOption hidden-xs hidden-md"><span>OR</span></div>
                  </Col>
                  <Col xs={12} md={5}>
                    <button
                      className="u-noBorderRadius u-fullWidth btn btn-yellow"
                      onClick={this.onPaypalSubmit}
                      value="payPal">
                      Checkout with <img src="/public/build/images/paypal.png" />
                    </button>
                  </Col>
                </Row>
                <div className="Checkout-creditCardform">
                  <form data-parsley-validate onSubmit={this.onSubmit} ref="paymentForm">
                    <div className="Checkout-creditCard form-group parsley-input-validate-container">
                      <Row>
                        <Col xs={12} md={8} mdOffset={2}>
                          <div className="Checkout-creditCardLogo">
                            {this.state && this.state.cardLogo ? (
                              <img src={this.state.cardLogo} />
                            ) : (
                              <img src="/public/build/images/cc-alt.png" />
                            )}
                          </div>
                          <InputElement
                            id="creditCard"
                            ref="creditCard"
                            name="cardNo"
                            type="text"
                            defaultValue={ cardNo }
                            placeholder="*Card Number"
                            mask="9999 - 9999 - 9999 - 9999"
                            maskChar= {null}
                            className="Checkout-creditCardNo form-control"
                            data-parsley-error-message="Invalid Card No."
                            required
                            data-parsley-trigger="focusout"
                            autoComplete="off"
                          />

                          <Input
                           name ="cardType"
                           type="hidden"
                           ref="cardType"
                           value={this.state.cardType}
                           onChange={this.handleFieldUpdate}
                            />
                        </Col>
                      </Row>
                    </div>
                    <Row>
                      <Col xs={12} md={8} mdOffset={2}>
                        <div className="Checkout-cardHolder form-group parsley-input-validate-container">
                          <Input
                            name="cardHolderName"
                            type="text"
                            value={cardHolderName}
                            placeholder="*Cardholder Name"
                            className="form-control"
                            onChange={this.handleFieldUpdate}
                            data-parsley-pattern="^[A-z ]+$"
                            data-parsley-error-message="Invalid Cardholder Name"
                            required
                            data-parsley-trigger="focusout"
                          />
                        </div>
                      </Col>
                    </Row>
                    <div className="u-lineThrough"><span>VALID DATES</span></div>
                    <Row>
                      <Col xs={6} md={3} mdOffset={1}>
                        <div className="form-group parsley-input-validate-container">
                          <select
                            name="expireMonth"
                            value={expireMonth}
                            onChange={this.handleFieldUpdate}
                            required
                            data-parsley-error-message="Please select expiry month"
                            data-parsley-trigger="focusout"
                          >
                            <option value="" disabled>*Month</option>
                            {
                              this.state.months.map((month, index) => {
                                return (
                                  <option value={month.value} disabled={month.disabled} key={"month_" + index}>{month.value}</option>
                                )
                              })
                            }
                          </select>
                        </div>
                      </Col>
                      <Col xs={6} md={3}>
                        <div className="form-group parsley-input-validate-container">
                          <select
                            name="expireYear"
                            value={expireYear}
                            onChange={this.handleFieldUpdate}
                            required
                            data-parsley-error-message="Please select expiry year"
                            data-parsley-trigger="focusout"
                            >
                            <option value="" disabled>*Year</option>
                            {
                              this.state.years.map((year, index) => {
                                return (
                                  <option value={year} key={"year_" + index}>{year}</option>
                                )
                              })
                            }
                          </select>
                        </div>
                      </Col>
                      <Col xs={6} md={3}>
                        <div className="form-group parsley-input-validate-container">
                          <Input
                            name="securityCode"
                            type="text"
                            value={securityCode}
                            placeholder="*CVC/CVV"
                            maxLength={4}
                            minLength={3}
                            className="form-control form-controlCvc"
                            onChange={this.handleFieldUpdate}
                            data-parsley-type="digits"
                            data-parsley-error-message="Invalid Security Code"
                            required
                            data-parsley-trigger="focusout"
                          />
                        </div>
                      </Col>
                      <Col xs={6} md={1}>
                        <OverlayTrigger placement="top" container={document.getElementById("cvvContainer")} ref="overlayCcvPopover" trigger="click" rootClose overlay={cvvPopover}>
                          <div className="Checkout-question" id="cvvContainer">
                            <FontAwesome name="question" />
                          </div>
                        </OverlayTrigger>
                      </Col>
                    </Row>
                  </form>
                  <form className="hide" ref="finalPaymentForm" method="post" action={API_PLACE_ORDER_URL}>
                    <input type="hidden" name="details" value={this.state.formDetails} />
                    <input type="submit" value="Submit" />
                  </form>
                </div>
                <Row>
                  <Col xs={12} md={6}>
                    <button
                      className="u-noBorderRadius u-fullWidth btn btn-secondary"
                      onClick={ this.handlePrevPage }
                      value="Back">
                      Back to delivery address
                    </button>
                  </Col>
                  <Col xs={12} md={4} mdOffset={2}>
                    <button
                      className="u-noBorderRadius u-fullWidth btn btn-default"
                      onClick={ this.validateFields }
                      value="card"
                      disabled={ this.state.disabledPaymentBtn }>
                      Pay Now
                    </button>
                  </Col>
                </Row>
              </Col>
            </Row>
          </div>
          <div className="Checkout-trust simpleBox u-centeredContent u-marginT120 hidden-md hidden-lg">
            <ul className="Checkout-trustList">
              <li className="Checkout-trustItem">
                <img src="public/images/trustPoint1.png" />
              </li>
              <li className="Checkout-trustItem">
                <img src="public/images/trustPoint2.png" />
              </li>
              <li className="Checkout-trustItem">
                <img src="public/images/trustPoint3.png" />
              </li>
              <li className="Checkout-trustItem">
                <img src="public/images/trustPoint4.png" />
              </li>
            </ul>
          </div>
      </div>
    )
  }
}
