### ISSUE TITLE
Problems with the android os

### ISSUE THREAD

**Issue by andalt** [sanniassin/react-input-mask#52]
If maskChar !== "" =>  value + 1 symbol

Screenshot:

![s60802-121034](https://cloud.githubusercontent.com/assets/8655528/17323531/2bf5aab6-58ab-11e6-8f80-a6d18f037437.png)

**Comment by sanniassin** [comment]
@andalt Нужен пример кода, последовательность шагов для воспроизведения бага и описание окружения (устройство, версии Андроида и брузера). Сейчас из описания трудно что-то понять.

**Comment by andalt** [comment]
@sanniassin

**Comment by andalt** [comment]
@sanniassin 

Устройства на которых обнаружен дефект:
Samsung Galaxy S6, Android 6.0.1, Chrome 51.0.2704.81
Nokia Lumia 930, Windows 10 Mobile, Microsoft Edge 25.10586.420.0
Meizu m2, Android 5.1, Chrome 52.0.2743.98

Пример кода: <InputElement mask="99.99.9999" maskChar="_"/>

Последовательность шагов: При вводе значений в поле input в value после каждого ввода попадает на один символ больше (на символ маски (в моем примере символ "_")).
В моем случае при срабатывании события onblur срабатывает валидация на поле, и в итоге в value приходит на один символ больше. (Пример: 15.06.1984_).

#51 Здесь тоже упоминают об этой проблеме

Прошу помощи в решении данной проблемы. Заранее спасибо!

**Comment by sanniassin** [comment]
@andalt Добавил фикс для #51. Посмотри пожалуйста остался ли баг.

**Comment by andalt** [comment]
@sanniassin Проверил везде где только возможно). Вроде все ок. Спасибо! Жду на npm.

**Comment by sanniassin** [comment]
@andalt Спасибо! Обновил на npm
