### ISSUE TITLE
the mask do not pay attention to the suffix permanent char

### ISSUE THREAD

**Issue by F4b1n0u** [sanniassin/react-input-mask#54]
Hello guys

If I use the following code

```xml
<InputMask
  type="text"
  mask="999 €"
  maskChar=""
  alwaysShowMask={true}
  value={10}
/>
```

I expect to see an input with "10 €" display in it
instead I have "10"

I have the impression all the mask on the right is omitted

**Comment by F4b1n0u** [comment]
after having a look into the code, I notice we dpay attention only to the prefix permanent characters (getPrefix function into formatValue function)
maybe a kind of getSuffix function could help to format the field properly
but I do not master the project so, I can't tell :)

**Comment by sanniassin** [comment]
@F4b1n0u It's not about suffix itself, it's about masking values with variable length. While masking requires a lot of hacks and workarounds for different browsers, i'm trying to keep code as simple as possible and not implement things which can be easily done outside of react-input-mask.

With your case you can put ```div``` under your input and put there transparent ```span``` with input value + colored one with ' €' suffix.
