### ISSUE TITLE
Clean value depending on state

### ISSUE THREAD

**Issue by arthurcouto** [sanniassin/react-input-mask#55]
There's a way to set state.value as empty depending on another state? I have a form and after it has been sent, I need to clean all input fields.

I'm currently doing it like this:

<InputElement type='tel' ref='cellphone' required styleName='form-info__cel' placeholder='Celular*' mask='(99) 99999-9999' onBlur={(event) => {
            this.validateCellphone(event.target.value.replace(/[^\d]+/g, ''))
          }} />

[...]

this.refs.cellphone.state.value = ''

but this raises an error on browser console:

Cannot update during an existing state transition (such as within  render or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to componentWillMount.

is there another way?

**Comment by sanniassin** [comment]
@arthurcouto Please show a full code of your component. Looks like you shouldn't assign state values directly in ```this.refs.cellphone.state.value = ''```. Look at Notes section – https://facebook.github.io/react/docs/component-api.html#setstate
