### ISSUE TITLE
onChange is being called on focus

### ISSUE THREAD

**Issue by diegodoumecq** [sanniassin/react-input-mask#56]
Why is onChange being called when focusing the input? I understand that there are some cases where it is needed but if the value is not changed then maybe we shouldn't call the onChange event?

Also. we need to store the clean value of the input without the added characters of the mask for obvious reasons and we were surprised to see that this library doesn't store a clean input value that we can just access through the change event.

**Comment by sanniassin** [comment]
@diegodoumecq Agreed about onChange calls when nothing changed.

About clean value – it's not so obvious for cases like +1 8__ 123___ (when you have some empty character between filled ones) and it can be easily done in your code. This component is not designed to be feature-rich. It's a simple drop-in replacement for native input which trying to control as few things as possible and allows you to add specific features in your own input wrapper.

**Comment by diegodoumecq** [comment]
Much appreciated!

Its a shame though since this is probably the best implementation of a masked input that I've seen.
