### ISSUE TITLE
Issue with v0.7.4 and autoFocus

### ISSUE THREAD

**Issue by golmansax** [sanniassin/react-input-mask#58]
I believe the following line throws an error if an input has `autoFocus` set to true.  https://github.com/sanniassin/react-input-mask/commit/f2997b3ef83485b456ae5fa2aac1c59f366e37d7#diff-444a3d04aeca567b0492915f6ad4ee82R698

When the component loads, `autoFocus` makes it so that `onFocus` is called.  This calls `getInputValue`, which breaks because `this.refs.input` is `null`.

Let me know if you want any more info!

**Comment by sanniassin** [comment]
@golmansax Fixed in 0.7.5. Thanks!

**Comment by golmansax** [comment]
@sanniassin props for addressing so quickly! 👍
