### ISSUE TITLE
Not obvious for user, whether he should enter a mask char or not if `alwaysShowMask` is `false`

### ISSUE THREAD

**Issue by le0nik** [sanniassin/react-input-mask#59]
For example, we have a date mask `99/99/9999`

User enters `01`.
What should he enter next: digit or slash(`/`)? It's non-obvious and user can only guess and learn this behavior(which is not good UX).

It would be much better, if the plugin added next char automatically, if it's a mask char.

So in our case, when user types `01` he'd see `01/`.

I've already fixed it in my project and can submit a PR. Is this something you'd consider merging in?

**Comment by sanniassin** [comment]
@le0nik Agree. PR may help because i'm little busy right now.

**Comment by le0nik** [comment]
PR: https://github.com/sanniassin/react-input-mask/pull/60
