### ISSUE TITLE
Mask with trailing chars not working

### ISSUE THREAD

**Issue by mzedeler** [sanniassin/react-input-mask#61]
If I use a mask like this:

```
<InputElement mask="999.999,99 kr." [...] />
```

The trailing " kr." is omitted.

**Comment by jorions** [comment]
Bump this issue. Can't do percentages because of this limitation.

**Comment by mzedeler** [comment]
There is a workaround: if you switch the guide on and use a variable length mask (such as the number mask provided with text-mask), it should work.
