### ISSUE TITLE
How to get the raw value?

### ISSUE THREAD

**Issue by shin-monkey** [sanniassin/react-input-mask#67]
Any getRaw() method available?

**Comment by sanniassin** [comment]
@shin-monkey No. If you know the mask, you can clean it yourself. For digits just use simple ```str.replace(/^[0-9]/g, '')```

**Comment by pudgereyem** [comment]
For other peoples reference: small typo above, should be `str.replace(/[^0-9]/g, '')`

**Comment by WalissonPires** [comment]
https://github.com/sanniassin/react-input-mask/issues/25#issuecomment-1050817718
