### ISSUE TITLE
Clear value of component

### ISSUE THREAD

**Issue by mihrich** [sanniassin/react-input-mask#68]
Is that possible?
In react that possible as:
`this.setState({'value':''});`
How to do it for InputElement? 

Thanks.

P.S Reset form not work for InputElement.

**Comment by alymenbr** [comment]
One way to solve it is creating a wrapper component, like this:

`
import React from 'react';
import InputElement from 'react-input-mask'

export default class MaskedInput extends React.Component {

  componentWillReceiveProps(nextProps){
    if(!nextProps.value)
      this.refs.inputElement.setState({value: ""})
  }

  render() {
    return (
      <InputElement ref="inputElement" {...this.props}/>
    )
  }
}
`

**Comment by thoughtassassin** [comment]
I am also having an issue when I am trying to reset a form with an InputMask. All of my other input reset properly but the InputMask retains its value.

**Comment by ramrami** [comment]
I've tried what @alymenbr suggested but didn't work for me until I used `this.refs.inputElement.value=''`. It's not React style, but it fix the problem for now 😄

**Comment by zgrybus** [comment]
@sanniassin Is there any better workaround? I'm using `react-hook-form` and when I send `undefined` value retains :/
