### ISSUE TITLE
No way to focus input

### ISSUE THREAD

**Issue by keepitreal** [sanniassin/react-input-mask#72]
Calling `input.focus()` using a `refs` object seems to cause input mask to not work and I cannot type within the input at all.

e.g.:
```
this.inputEl.refs.input.focus();
```

Is there some provided way to focus the input?

**Comment by mqklin** [comment]
@keepitreal 
```
<div ref={r => this.inputWrapper = r}><ReactInputMask /></div>
...
this.inputWrapper.querySelector('input').focus();
```

**Comment by alex-shamshurin** [comment]
Yep, this works, thanks! I spent two hours to figure out how to focus() it.
