### ISSUE TITLE
setSelection selects whole input

### ISSUE THREAD

**Issue by jonashaag** [sanniassin/react-input-mask#74]
Only happens on Android.

Our mask: `9999 9999 ...`

1. User types `1234`
2. `onKeyPress` is triggered
3. [This](https://github.com/sanniassin/react-input-mask/blob/c1ea5bb010c1a70c71dbd6f4c0fe61093ed7337d/InputElement.js#L596) returns 5
4. [This](https://github.com/sanniassin/react-input-mask/blob/c1ea5bb010c1a70c71dbd6f4c0fe61093ed7337d/InputElement.js#L303) is executed with `selectionStart = 5` and `selectionEnd = 5` => input is selected entirely instead of only moving the cursor.

As a temporary workaround, we have monkey patched the `setSelection` method as follows:

```js
  inputElemRef (inputElem) {
    if (inputElem === null)
      return
    const origSetSelection = inputElem.setSelection
    inputElem.setSelection = function (start, end) {
      const len = inputElem.getInputDOMNode().value.length
      if (start > len)
        start = len
      if (end > len)
        end = len
      return origSetSelection(start, end)
    }
  }

```

**Comment by sanniassin** [comment]
@jonashaag Android version, browser version, phone/tablet model?

**Comment by jonashaag** [comment]
4.4.2, HTC One mini, Android Browser 4.0 (WebKit 534.30)

**Comment by jonashaag** [comment]
bump

**Comment by sanniassin** [comment]
@jonashaag Nice bump, because my notifications was broken :) Can you make a repo with simple page which always fails? I can't reproduce but not sure if it related to Android version or my code.

**Comment by jonashaag** [comment]
Seems to be a bug in Android, this is the workaround: https://github.com/digitalBush/jquery.maskedinput/pull/50/files#diff-dc902f8c4f1205b11a31a844d30dfe49R69

I'm not sure if we can use the `setTimeout(..., 0)` approach when we don't use `setSelectionRange` though

**Comment by sanniassin** [comment]
@jonashaag I still need a repository with minimal project to reproduce this issue and test workaround.
