### ISSUE TITLE
Mask with conditions

### ISSUE THREAD

**Issue by MikeDevice** [sanniassin/react-input-mask#75]
How about mask with conditions support?

For example, I need an input with time mask.

Time examples:
```
00:00
12:59
19:20
23:45
```

The rules for this time are:

1. The first number can be from `0` to `2`
2. Second number can be from `0` to `9` if first number is `0` or `1`, otherwise -- from `0` to `3`
3. ...

I can't do this with current functional, because each `formatChar` is undependent

**Comment by Pau1fitz** [comment]
would also be convenient for the date. Currently, I can enter `54/54/2017`

**Comment by sanniassin** [comment]
@MikeDevice @Pau1fitz It could be implemented with a change of ```formatChars``` property when user inputs something.

```js
render() {
  var dateValue = this.state.dateValue;
  var mask = "12:34"
  var formatChars = {
    '1': '[0-2]',
    '2': dateValue.startsWith('2') ? '[0-3]' : ['0-9'],
    '3': '[0-5]',
    '4': '[0-9]'
  };
  return <InputMask mask={mask} formatChars={formatChars} value={dateValue} />;
}
```

I prefer to keep ```react-input-mask``` as simple as possible. It supposed to handle browser-specific hacks for masking, not to be a feature-rich component.

**Comment by Pau1fitz** [comment]
@sanniassin have you any idea how you would do this for the date?

i.e. `9/9/2017` so it becomes `09/09/2017`?

**Comment by mmsdiego** [comment]
@sanniassin Have an example functional?

**Comment by sanniassin** [comment]
Now it can be implemented with `beforeMaskedValueChange`.

**Comment by leonardosalles** [comment]
Any examples on that??? Missing docs about... I need to change the mask depending on value.

**Comment by sanniassin** [comment]
@leonardosalles Look at the last example on the [demo page](http://sanniassin.github.io/react-input-mask/demo.html).
