### ISSUE TITLE
Windows Mobile 8.1 Update 2 IE 11 Problem

### ISSUE THREAD

**Issue by martysupple** [sanniassin/react-input-mask#78]
Here is a simple React component (using TypeScript) that only allows the first character to be entered, subsequent characters are not updating state value. Seems possibly to be related to onKeyPress/onKeyDown handling in InputElement.js. Using version 0.7.9. Can repro using IE 11 emulation as well as on actual windows phone.

```
import { render } from "react-dom";
import * as React from "react";
import * as InputElement from "react-input-mask";

class App extends React.Component<void, any> {
    constructor() {
        super();
        this.onChange = this.onChange.bind(this);
        this.state = {
            value: "",
            mask: "9999-9999-9999-9999"
        };
    }

    onChange(e: React.ChangeEvent<HTMLInputElement>): void {
        const val: string = e.target.value;
        const newState = {
            mask: "9999-9999-9999-9999",
            value: val
        };
        this.setState(newState);
    }

    render(): JSX.Element {

        return (
            <InputElement {...this.state} onChange={this.onChange}  />
        )
    }
}

render(<App />
    ,
    document.getElementById("root")
);
```

**Comment by sanniassin** [comment]
@martysupple Check this pens:
* Updated one. Should work (i hope): http://codepen.io/sanniassin/pen/MpNaVY
* Old one. Should fail: http://codepen.io/sanniassin/pen/BWXoxG

If update one works i will publish it on npm.

**Comment by martysupple** [comment]
Looks good thanks!

Marty
