### ISSUE TITLE
Copy/paste masking leaving extra characters

### ISSUE THREAD

**Issue by reintroducing** [sanniassin/react-input-mask#8]
When you mask using '9999 9999 9999 9999' and use a maskChar of null, everything works as expected if you in put 4242 4242 4242 4242.  Now, select all and paste a 15 digit number instead (as is the case with an Amex card) and the remaining 2 is left with the number.  

Expected result is that the original number would be completely removed and only the new, 15 digit number would be present.

**Comment by sanniassin** [comment]
Could you make an example at codepen.io? Can't reproduce it here http://codepen.io/anon/pen/zGQNEz

1. Put "4242 4242 4242 4242" in input
2. Copy "3442 424242 99999"
3. Select all in input
4. Paste "3442 424242 99999"

Nothing remains at the end

**Comment by reintroducing** [comment]
Here you go: http://codepen.io/reintroducing/pen/ZbpMdv

I removed the onChange and you can see it now.

**Comment by sanniassin** [comment]
It will not work without onChange handler as react-input-mask itself doesn't know about amex or anything else, so you need to change mask property from parent component.

**Comment by reintroducing** [comment]
I'm not looking to change the mask at that point, I'd just like it to be able to hold 15 digits instead of 16 and not apply one more to the end.  If you type in 15 characters without copy/paste everything is fine and the mask is applied with only 3 digits on the last set.  That's what I'd expect to happen if I only pasted 15 as well.

The reason why this is important to me is because this sits in a backbone application as one of the only React components in the codebase and I don't necessarily have a state manager in a parent component to do it the proper way.  I don't mind the mask not changing, I just don't want it to add one more digit when all I pasted was 15.

**Comment by sanniassin** [comment]
Got you. Will look into it tomorrow.

**Comment by reintroducing** [comment]
Like I said before, this component is fantastic and this is really a minor gripe for my particular use case so I really do appreciate you taking the time to look into it.

**Comment by sanniassin** [comment]
@reintroducing Please try latest version from this repo.

**Comment by reintroducing** [comment]
@sanniassin Works perfect, thanks! Please do publish it to npm when you get a chance, appreciate all the help.

**Comment by reintroducing** [comment]
@sanniassin Just wanted to make sure 0.3.0, the version on npm, is the one with this fix in it? I apologize but I lost track of what's what :\

**Comment by sanniassin** [comment]
Yes. You can look at changes before version 0.3.0 commit here – https://github.com/sanniassin/react-input-mask/commits/master

**Comment by reintroducing** [comment]
gotcha, thanks :)
