### ISSUE TITLE
Third party lib integration

### ISSUE THREAD

**Issue by IcanDivideBy0** [sanniassin/react-input-mask#80]
Hello,
Would you accept a PR that allow thirs party lib for the input component ? Playing with react-toolbox, and planing on doing something like :

```js
import { Input } from 'react-toolbox'
import InputElement from 'react-input-mask'

<InputElement Component={Input} getInputRef={ref => ref.getWrappedinstance().inputNode} />
```

* specify any react component as input via the `component` prop
* specify a `getRef` prop so `InputElement` could still track the input values (the `getWrappedInstance` stuff is specific to react-toolbox)

**Comment by sanniassin** [comment]
@IcanDivideBy0 Unfortunately this kind of integration will be very buggy because ```react-input-mask``` hardly relies on raw event handlers and props of ```<input />``` element and contains a lot of dirty hacks as workarounds for browser bugs (especially for browsers in Android < 5.0 and Windows Phone).

So while It's a good feature and can work for specific components in specific environments i can't make it stable enough at this moment.

**Comment by IcanDivideBy0** [comment]
@sanniassin I don't get it, all the hacks pass through the same pipe : get the input node with `getInputDOMNode`, then install hack on node.

So as long as the correct input node is referenced everything should works the same. Browser compatibility isn't related to how input node ref is passed, this is react concern.

Can you please take a look at the PR and point me to anything that could go wrong assuming the correct ref is passed ?

**Comment by sanniassin** [comment]
@IcanDivideBy0 It works fine with simple Material Design-styled component. But it fails if component listens for key events and changes input value.

Tried to integrate with [react-typeahead](https://github.com/fmoo/react-typeahead) and ```npm run test``` fails at 15 tests. Look at [this branch](https://github.com/sanniassin/react-input-mask/tree/80-third-party-inputs).

Also some components like [react-autosuggest](https://github.com/moroshko/react-autosuggest) replaces default input properties with it's own API which makes them incompatible with proposed integration API.

While it works for [react-toolbox](https://github.com/react-toolbox/react-toolbox) i don't want to implement such a dangerous feature which requires disclaimer in docs and can broke your app if new version of third-party component starts to handle key events.

**Comment by IcanDivideBy0** [comment]
OK, seems fair enouth. I'll close the PR/issue and stick to my fork so.

Thanks for your time
