### ISSUE TITLE
Default handlers prevent keyup event

### ISSUE THREAD

**Issue by jonashaag** [sanniassin/react-input-mask#82]
The code for the default keydown/keypress handlers uses `preventDefault` in case the input changes. This prevents the `keyup` event from being triggered.

**Comment by sanniassin** [comment]
@jonashaag Triggers for me. Can you look if it shows alert on keyup and tell more about your browser and os if it doesn't?

https://codepen.io/sanniassin/pen/LpvMyx

**Comment by jonashaag** [comment]
It doesn't trigger if I change the pattern to something with letters and then enter letters. Tested on various Android devices. Digits always work, but letters don't, for some reason.

**Comment by sanniassin** [comment]
@jonashaag Sounds like an Android issue especially if Android is older than 5.0. Is ```keydown``` firing in your app on iOS and desktop browsers?

**Comment by jonashaag** [comment]
Yes, it is, as well as `keyup`. We don't use it though, but I just attached

```js
        onKeyDown={() => console.log('keydown')}
        onKeyUp={() => console.log('keyup')}
```

to check and it works

**Comment by sanniassin** [comment]
react-input-mask 2.0.0 doesn't listen to any key events, so it shouldn't affect them.
