### ISSUE TITLE
How to preventDefault of arrow up & down

### ISSUE THREAD

**Issue by krzysztofpniak** [sanniassin/react-input-mask#85]
I would like to preventDefault when user press arrow down and arrow up keys. Expected behavior is to keep cursor in the same position while pressing that keys.

I tried following code(without success) which works fine with normal inputs:
```
<InputMask
                    value={model.value}
                    onChange={handleChange}
                    mask="9999-99-99 99:99"
                    onKeyDown={e => {if (e.keyCode === 38) { e.preventDefault()} }}/>
```

**Comment by krzysztofpniak** [comment]
Really sorry, I missed one important detail.
I'm setting value after preventing default. Without setting value it works like in your codepen.
My goal is to increment date parts(year, month, day, etc) depending on cursor position using arrows.
Any ideas how can I achieve this?

**Comment by sanniassin** [comment]
@krzysztofpniak Can you fork my snippet and add date increment functionality to it?

**Comment by krzysztofpniak** [comment]
Ok

**Comment by krzysztofpniak** [comment]
Here it is:

**Comment by sanniassin** [comment]
@krzysztofpniak Same issue with pure React. Cursor moves both on change inside keydown handler and on change with setInterval: https://codepen.io/sanniassin/pen/dRYXKO

Pretty long thread in React's repo: https://github.com/facebook/react/issues/955

You have to save `selectionStart` and `selectionEnd` in keydown handler and restore them in `componentDidUpdate` or in `setTimeout` or `requestAnimationFrame`. If i remember correctly IE8 or some Androids doesn't update cursor position immediately after value change, so `componentDidUpdate` only might be not enough.

The funny thing is that `react-input-mask` has an ugly workaround for this behaviour. It restores cursor position in `requestAnimationFrame` callback, but it do that only on characters removal when `Backspace` or `Delete` is pressed.

**Comment by krzysztofpniak** [comment]
Thank you again for everything you’ve done. It helped me to solve the problem.
