### ISSUE TITLE
Error: Cannot find module 'react-input-mask'

### ISSUE THREAD

**Issue by jrodl3r** [sanniassin/react-input-mask#87]
Doing everything as instructed.... Running a webpack build, and I'm baffled as to why this isn't working, and why it's giving this error when i can see that it's obviously installed, listed in pkg.json, and it even works if i just ad-hok it in before building (reactGo/reactGo) my project.

Weird one....

**Comment by sanniassin** [comment]
@jrodl3r Try latest update (0.9.1). There was an invalid path to compiled CommonJS module in package.json in 0.9.0.
