### ISSUE TITLE
Like limiting a number before the point, an integer value?

### ISSUE THREAD

**Issue by nato90** [sanniassin/react-input-mask#88]

**Comment by sanniassin** [comment]
@nato90 Can you provide more accurate description?

**Comment by nato90** [comment]
For example a field that only accepts five integers with two decimals for example that allows to capture 456.32 but not the number 4567.32 since it would only accept 3 integers and 2 decimals

**Comment by sanniassin** [comment]
@nato90 I won't implement this feature for now. Look at [Text Mask](https://github.com/text-mask/text-mask). It has much more flexible mask logic.
