### ISSUE TITLE
onFocus event throws the onChange event when the value is empty using the mask attribute at the first time.

### ISSUE THREAD

**Issue by jalanya** [sanniassin/react-input-mask#90]
Hi,
onFocus event throws the onChange event when the value is empty using the mask attribute at the first time. I think that we should not throws the onChange event onFocus until that the user really changes the value

In the onFocus event, I think that the fix could be below:
`var isInputValueChanged = inputValue !== event.target.value;`

With the additional condition.
`var isInputValueChanged = inputValue !== event.target.value && inputValue !== _this2.formatValue("")`

**Comment by sanniassin** [comment]
@jalanya It triggers onChange because value is actually changed. If i have custom input placeholder implementation then i need to know when input becomes non-empty to hide placeholder. Why do you want to not trigger onChange?

**Comment by jalanya** [comment]
hi @sanniassin,
Because, we do not want to trigger the validations once the user goes to the Date input at the first time even the component has the mask '_99/99/9999'_. Take a look at the short video (8 secs) http://recordit.co/azzmiVWVed.

We have a wrapper component over react-input-mask with the structure below:

`<TextInputMask
      mask="99/99/9999"
      placeholder="mm/dd/yyyy"
      placeholderAlwaysDisplayed
      value={...this.StateProp('dateOfBirth')}
      onChange={...hangleChange('dateOfBirth')}/>`

When an input's value is changed through user interaction, we trigger some validations on the OnChange event and we show red messages at the top the input as you can have seen in the short vide above. However, this value '__/__/____' is being evaluated as a change in the onFocus.

**Comment by sanniassin** [comment]
@jalanya Check for event type to ignore onFocus changes.
```js
onChange = (event) => {
  if (event.type === 'focus') {
    return;
  }
  // usual change handling
}
```

**Comment by tibuurcio** [comment]
Just stumbled upon this and the fix above solved my problem.

The `focus` event was being thrown on first click and caused the component to stay in an infinite loop, but only in Safari. Ignoring `type === 'focus'` fixed it.
