### ISSUE TITLE
How to pre-populate country code

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [sanniassin/react-input-mask#94]
Suppose that I'm using mask="+6\2 999 99999999" . In this case, +62 will not populate until I click on the textbox. Is there any way to make it prepopulated?

**Comment by sanniassin** [comment]
@Abhijeetjaiswalit Add `alwaysShowMask={true}`
```jsx
<InputMask value={this.state.value} onChange={this.onChange} mask="+62 999 99999999" alwaysShowMask={true} />
```

**Comment by Abhijeetjaiswalit** [comment]
@sanniassin  Thank you show much.
