### ISSUE TITLE
how to make variable number of patterns to match?

### ISSUE THREAD

**Issue by SuperManEver** [sanniassin/react-input-mask#95]
I want to use input mask to match entered price for example 18.89

I do the following:
```javascript
<InputElement
      className={inputPriceClasses}
       name="fixedPrice"
       value={fixedPrice}
       onChange={updateHandler}
       placeholder="$0.00"
       type="text"
       mask="99.99"
       maskChar=""
  />
```

as you can see I use mask `mask="99.99"` and it does what it says, user can enter two digits, then dot and two more digits. But what I need is to specify that some variation in amount of digitst before "." is possible.

I'd like to be able (as a user) to enter 190.90 as well as 18.16, 1892.23 and so on.
Currently I only able to enter 12.78 (for example)

How can I do this ?

**Comment by sanniassin** [comment]
@SuperManEver No, because react-input-mask is supposed to be a simple solution for a fixed length masks.

Look at [Text Mask library](https://github.com/text-mask/text-mask). It supports more complicated formatting rules and has a price input example on demo page.
