### ISSUE TITLE
Ios issue: error on backspace

### ISSUE THREAD

**Issue by SlevenRobbert01** [sanniassin/react-input-mask#96]
v1.0.5
When using component on iOS device. it gives an error when using backspace.

TypeError: _this2.getInputDOMNode().parentElement is not a function. (In '_this2.getInputDOMNode().parentElement()', '_this2.getInputDOMNode().parentElement' is an instance of HTMLDivElement)

**Comment by sanniassin** [comment]
@SlevenRobbert01 Thank you for reporting. Published v1.0.6 with a fix.
