### ISSUE TITLE
How to take masked formatted value in redux form?

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [sanniassin/react-input-mask#97]
@sanniassin   I was using it with redux form. The problem arises when I tried to take the same masked value as it was showing in textbox. I mean on form submit the value for 111111 111111 1111 goes like 111111111111111 while I want the same format that is showing in textbox that is 111111 111111 1111 . As ref is not working with redux form Field's so is there any way to take masked value?

**Comment by sanniassin** [comment]
@Abhijeetjaiswalit Can you make a demo?

**Comment by Abhijeetjaiswalit** [comment]
This is my render method orlets just say stateless component:: 
 
renderKTPField(field) {
    const { meta: { touched, error } } = field;
    const className = `form-group ${touched && error ? 'has-danger' : ''}`
    return (
      <div className={className}>
        <InputElement id="KTP"
          {...field.input}
          mask="999999 999999 9999"
          maxLength={18}
          className="form-control"
          maskChar="" />
        <div className="text-help">
          {touched ? error : ''}
        </div>
      </div>
    );
  }

This is form that I am using for a component:

<form onSubmit={handleSubmit(this.submitHandler.bind(this))}>
<Field
      name="KTP"
      onChange={(e) => { this.setState({outputKTPValue: e.target.value})}}
                                component={this.renderKTPField}
  />
</form>



Submit Handler:

   submitHandler(values) {
    let temp = values.KTP;   //temp = 3171022105860001 if I enter 317102 210586 0001 and submit the                                                                                          
                                                                                                                                                              form.
    let data = {
      ktp: temp,
      id: localStorage.getItem('id')
    }
    this.saveKtp(data);
    this.props.start();
  }

**Comment by sanniassin** [comment]
@Abhijeetjaiswalit Put it on https://codesandbox.io please

**Comment by Abhijeetjaiswalit** [comment]
@sanniassin  sandbox in giving 401 error while adding a package.

**Comment by sanniassin** [comment]
@Abhijeetjaiswalit Try https://www.webpackbin.com or any other code playground service

**Comment by Abhijeetjaiswalit** [comment]
However i don't know why code is not working here. but i have mentioned the description .
 here is the link https://codesandbox.io/s/6m3kvJAQ

**Comment by Abhijeetjaiswalit** [comment]
The concern is if i initialize the field the value comes in the form of whole string. after submitting it without onblur or any change, it also saves it without space. so i just can't take the masked value on just only page render without doing any change or blur event.

**Comment by sanniassin** [comment]
@Abhijeetjaiswalit You're removing spaces with
```js
var KTP = temp.replace(/ /g, '');
```

**Comment by Abhijeetjaiswalit** [comment]
Yeah. That is on submit. I want to take default value that is in the text box that comes on page render from back end. So i was expecting a way to take value of newly rendered element in masked format. Because taking value using ref doesn't work here.

**Comment by sanniassin** [comment]
@Abhijeetjaiswalit https://codesandbox.io/s/yPOQP9m1z

**Comment by sanniassin** [comment]
You can attach ref to `InputElement` itself or get an input inside `<Field />` with this code.

```js
const fieldDiv = ReactDOM.findDOMNode(this.field);
const input = fieldDiv.querySelector('input');
alert(input.value);
```

**Comment by Abhijeetjaiswalit** [comment]
thank you so much @sanniassin
