### ISSUE TITLE
Error for latest React (15.6.1)

### ISSUE THREAD

**Issue by ixrock** [sanniassin/react-input-mask#98]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
"react": "^15.6.1",
"react-dom": "^15.6.1",
```

Problem seems to be related to this code chunk:
```
    return _react2.default.createElement('input', _extends({ ref: function ref(_ref) {
        return _this2.input = _ref;
      } }, props, { onFocus: _this2.onFocus, onBlur: _this2.onBlur }));
```

**Comment by ixrock** [comment]
BTW, why not keeping source files in npm as well? Probably this is issue releated to compiled code only.

**Comment by sanniassin** [comment]
@ixrock Can't reproduce. Can you  make a demo?

Sources aren't included to reduce package size. Also node_modules is usually excluded from processing with babel-loader so `import InputMask from 'react-input-mask/src'` won't compile anyway.

**Comment by ixrock** [comment]
Problem solved by importing package as (i'm using it with typescript):

`import InputMask = require("react-input-mask/dist/react-input-mask.min.js");`
previously was:
`import InputMask = require("react-input-mask");`

Maybe it's better to specify "main" in package.json linked to compiled minified version?

**Comment by ixrock** [comment]
And btw, is it you maintainer for https://www.npmjs.com/package/@types/react-input-mask ?

**Comment by sanniassin** [comment]
@ixrock I'll appreciate if you'll share your project. Still want to make it work with a regular import.

About types – no i'm not a maintainer because i don't use TypeScript.

**Comment by ixrock** [comment]
It's private company repo, so cannot share it, sorry.
If you don't use typescript maybe you won't face this problem or maybe it's webpack's specific loader problem or who knows..
If you want to make it work with regular import just define `"main": "react-input-mask/dist/react-input-mask.min.js"` in `package.json`

**Comment by sanniassin** [comment]
@ixrock The weird thing is that i've set up TypeScript environment and it just works without any changes in import path or `main` field. Can you try to "broke" this project? It starts a webpack server with `npm run dev`.

[react-input-mask-test.zip](https://github.com/sanniassin/react-input-mask/files/1148469/react-input-mask-test.zip)

**Comment by ixrock** [comment]
Didn't run your project yet, but can suppose it's cause I don't use babel at all.
This is how loaded ts-files in my webpack's config:
```
module: {
  rules: [
    {
      test: /\.tsx?$/,
      use: 'awesome-typescript-loader'
    },
  ]
}
```

**Comment by sanniassin** [comment]
@ixrock Still works.

https://github.com/sanniassin/react-input-mask-ts-bug

**Comment by ixrock** [comment]
Hmm.. I found the problem and it works now for me with normal import:
`import InputMask from "react-input-mask"`

Recently I've updated typescript to latest version and probably something there was changed related how such form of import works:
`import InputMask = require("react-input-mask");`

I'm using such form of import for packages without types or for specific cases like for lodash:
`import isFunction = require("lodash/isFunction");` because if I'll do `import isFunction from "lodash/isFunction";` it says it has no default import and shows error..

Thanks for your help! 👍

**Comment by pbarbiero** [comment]
For what its worth, I am seeing this randomly with React 15.5.4 and webpack 3.3.0

Sometimes it works, sometimes it fails. Not using typescript.

Same exact error: `Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by sanniassin** [comment]
@pbarbiero Whether it disappears after page reload or specific page with specific js bundle always fails?

**Comment by pbarbiero** [comment]
We have code splitting, so several bundles. It appears to always fail when a second bundle tries to use it, and then it breaks it for all bundles after that.

**Comment by sanniassin** [comment]
@pbarbiero Do you use `require('react-input-mask')` instead of `import`? There is some issues with CommonJS build.

**Comment by pbarbiero** [comment]
We will just stick with the workaround for now.

Do you want to reopen this issue or would you like me to open a new one?

**Comment by sanniassin** [comment]
@pbarbiero New one will be better, thanks!

**Comment by sedenardi** [comment]
This is still an issue w/ using CommonJS `require()` and Webpack. Tested with v1.2.2.

```js
const InputMask = require('react-input-mask'); // React.createElement: type is invalid
const InputMask = require('react-input-mask/dist/react-input-mask.min'); // works
```

**Comment by sanniassin** [comment]
@sedenardi Why not use ES import syntax? Since modern versions of Webpack always use ES modules over CommonJS ones (https://github.com/webpack/webpack/issues/4742), you have to either import with
```js
import InputMask from 'react-input-mask';
```
or
```js
const InputMask = require('react-input-mask').default;
```

**Comment by sedenardi** [comment]
@sanniassin It's party of a fairly large project whose views haven't been cut over to ES import syntax yet. 

Appending `.default` to the require statement doesn't work either, resulting in this error:

`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Not sure if this makes a difference, but I'm doing server-side rendering. This error comes from the server when I render the markup.

**Comment by sanniassin** [comment]
@sedenardi I decided to get rid of ES module to avoid this kind of confusion. Going to release new version in a few days.
