### ISSUE TITLE
Wrong Typescript typings

### ISSUE THREAD

**Issue by dmydry** [sanniassin/react-input-mask#99]
Typescript 2.4.1
@types/react 15.0.35

Your interface ReactInputMaskProps extends from React.InputHTMLAttributes<HTMLInputElement>
but it should be from React.HTMLProps<HTMLInputElement>

**Comment by sanniassin** [comment]
@dmydry Hi. I'm not related to TS definitions, so i guess you should fill an issue in DefinitelyTyped repo instead or contact with definitions authors.
